<?php
require_once __DIR__.'/../config/config.php';require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/functions.php';zorunlu_rol('admin','yonetici');
$islem=$_GET['islem']??$_POST['islem']??'';$id=(int)($_GET['id']??$_POST['id']??0);$tur=$_GET['tur']??$_POST['tur']??'takim';if(!in_array($tur,['takim','bireysel'],true))$tur='takim';
if($_SERVER['REQUEST_METHOD']==='POST'){
    try{if(!csrf_check($_POST['csrf']??''))throw new RuntimeException('Güvenlik doğrulaması başarısız.');
        if($islem==='sil'){$kontrol=$pdo->prepare('SELECT COUNT(*) FROM takimlar WHERE grup_id=?');$kontrol->execute([$id]);if($kontrol->fetchColumn())throw new RuntimeException('Bu grupta kayıtlı takım olduğu için silinemez.');$pdo->prepare('DELETE FROM bireysel_fikstur_atislari WHERE fikstur_id IN (SELECT id FROM bireysel_fikstur WHERE grup_id=?)')->execute([$id]);$pdo->prepare('DELETE FROM bireysel_fikstur WHERE grup_id=?')->execute([$id]);$pdo->prepare('DELETE FROM bireysel_lig_kayitlari WHERE grup_id=?')->execute([$id]);$pdo->prepare('DELETE FROM gruplar WHERE id=?')->execute([$id]);flash_set('basari','Grup silindi.');}
        else{$ligId=(int)($_POST['lig_id']??0);$bolge=trim($_POST['bolge_adi']??'');$kategori=trim($_POST['kategori_adi']??'');$atisAlani=trim($_POST['atis_alani']??'');$q=$pdo->prepare('SELECT tur FROM ligler WHERE id=?');$q->execute([$ligId]);$ligTuru=$q->fetchColumn();if($ligTuru!==$tur)throw new RuntimeException('Seçilen lig grup türüyle uyumlu değil.');if($bolge==='')throw new RuntimeException('Bölge adı zorunludur.');if($tur==='bireysel'&&(!in_array($kategori,['Minikler','Yıldızlar','Gençler','Yetişkin','Kadınlar'],true)||$atisAlani===''))throw new RuntimeException('Bireysel grup için kategori ve atış alanı zorunludur.');if($tur==='takim'){$kategori=null;$atisAlani=null;}$grupAdi=$tur==='bireysel'?$bolge.' > '.$kategori:$bolge;
            if($islem==='duzenle'){$pdo->prepare('UPDATE gruplar SET lig_id=?,grup_adi=?,bolge_adi=?,kategori_adi=?,atis_alani=? WHERE id=?')->execute([$ligId,$grupAdi,$bolge,$kategori,$atisAlani,$id]);flash_set('basari','Grup güncellendi.');}
            else{$pdo->prepare('INSERT INTO gruplar(lig_id,grup_adi,bolge_adi,kategori_adi,atis_alani,sezon) SELECT ?,?,?,?,?,sezon FROM ligler WHERE id=?')->execute([$ligId,$grupAdi,$bolge,$kategori,$atisAlani,$ligId]);flash_set('basari','Grup oluşturuldu.');}
        }
    }catch(Throwable $e){flash_set('hata',$e->getMessage());}
    redirect(BASE_URL.'/admin/gruplar-ve-fikstur.php');
}
$duzenlenen=null;if($islem==='duzenle'&&$id){$q=$pdo->prepare('SELECT g.*,l.tur FROM gruplar g JOIN ligler l ON l.id=g.lig_id WHERE g.id=?');$q->execute([$id]);$duzenlenen=$q->fetch();if(!$duzenlenen){flash_set('hata','Grup bulunamadı.');redirect(BASE_URL.'/admin/gruplar-ve-fikstur.php');}$tur=$duzenlenen['tur'];}
$ligler=$pdo->prepare('SELECT * FROM ligler WHERE tur=? ORDER BY lig_adi');$ligler->execute([$tur]);$turLigleri=$ligler->fetchAll();
$takim=$pdo->query("SELECT g.*,l.lig_adi,COUNT(t.id) sayi FROM gruplar g JOIN ligler l ON l.id=g.lig_id LEFT JOIN takimlar t ON t.grup_id=g.id WHERE l.tur='takim' GROUP BY g.id ORDER BY l.lig_adi,g.grup_adi")->fetchAll();$bireysel=$pdo->query("SELECT g.*,l.lig_adi,COUNT(k.id) sayi FROM gruplar g JOIN ligler l ON l.id=g.lig_id LEFT JOIN bireysel_lig_kayitlari k ON k.grup_id=g.id WHERE l.tur='bireysel' GROUP BY g.id ORDER BY l.lig_adi,g.bolge_adi,g.kategori_adi")->fetchAll();$tumLigler=$pdo->query('SELECT * FROM ligler ORDER BY lig_adi')->fetchAll();
ob_start();?>
<div class="toolbar"><a class="btn btn-outline" href="<?= BASE_URL ?>/admin/ligler.php">← Ligler ve Sezon</a></div>
<?php if(in_array($islem,['ekle','duzenle'],true)): ?><section class="card"><div class="card-head"><h2><?= $islem==='ekle'?($tur==='takim'?'Yeni Takım Ligi Grubu':'Yeni Bireysel Lig Grubu'):'Grubu Düzenle' ?></h2></div><form method="post" class="form"><?= csrf_field() ?><input type="hidden" name="islem" value="<?= e($islem) ?>"><?php if($id): ?><input type="hidden" name="id" value="<?= $id ?>"><?php endif; ?><input type="hidden" name="tur" value="<?= e($tur) ?>"><div class="grid-2"><label>Bölge Adı *<input name="bolge_adi" required value="<?= e($duzenlenen['bolge_adi']??'') ?>" placeholder="Bursa - Balıkesir Bölgesi"></label><label>Lig *<select name="lig_id" required><option value="">Seçin</option><?php foreach($turLigleri as $lig): ?><option value="<?= (int)$lig['id'] ?>" <?= (int)($duzenlenen['lig_id']??0)===(int)$lig['id']?'selected':'' ?>><?= e($lig['lig_adi']) ?></option><?php endforeach; ?></select></label></div><?php if($tur==='bireysel'): ?><div class="grid-2"><label>Kategori *<select name="kategori_adi" required><option value="">Seçin</option><?php foreach(['Minikler','Yıldızlar','Gençler','Yetişkin','Kadınlar'] as $kategori): ?><option value="<?= $kategori ?>" <?= ($duzenlenen['kategori_adi']??'')===$kategori?'selected':'' ?>><?= $kategori ?></option><?php endforeach; ?></select></label><label>Atış Alanı *<input name="atis_alani" required value="<?= e($duzenlenen['atis_alani']??'') ?>" placeholder="Atış poligonu / tesis"></label></div><?php endif; ?><div class="form-actions"><button class="btn btn-primary"><?= $islem==='ekle'?'Grubu Oluştur':'Güncelle' ?></button><a class="btn btn-outline" href="<?= BASE_URL ?>/admin/gruplar-ve-fikstur.php">İptal</a></div></form></section><?php endif; ?>
<div class="grup-iki-sutun"><?php foreach(['Takım Ligi Grupları'=>[$takim,'takim'],'Bireysel Lig Grupları'=>[$bireysel,'bireysel']] as $baslik=>[$liste,$listeTuru]):?><section class="card"><div class="card-head"><h2><?= $baslik ?></h2><a class="btn btn-primary" href="<?= BASE_URL ?>/admin/gruplar-ve-fikstur.php?islem=ekle&tur=<?= $listeTuru ?>">+ Yeni Grup</a></div><?php foreach($liste as $g):?><div class="lig-fikstur-satir"><a href="<?= BASE_URL ?>/grup.php?id=<?= (int)$g['id'] ?>"><strong><?= e($listeTuru==='takim'?$g['grup_adi']:($g['bolge_adi'].' > '.$g['kategori_adi'])) ?></strong><small><?= e($g['lig_adi']) ?> · <?= (int)$g['sayi'] ?> <?= $listeTuru==='takim'?'takım':'sporcu' ?></small></a><div><a class="btn btn-sm" href="<?= BASE_URL ?>/admin/gruplar-ve-fikstur.php?islem=duzenle&id=<?= (int)$g['id'] ?>">Düzenle</a><form method="post" class="inline-form" onsubmit="return confirm('Grup silinsin mi?')"><?= csrf_field() ?><input type="hidden" name="islem" value="sil"><input type="hidden" name="id" value="<?= (int)$g['id'] ?>"><button class="btn btn-sm btn-danger">Sil</button></form></div></div><?php endforeach;?></section><?php endforeach;?></div>
<section class="card lig-fikstur-listesi"><div class="card-head"><h2>Lig Fikstürleri</h2><span class="badge">Turnuva fikstürleri Turnuvalar menüsünde</span></div><?php foreach($tumLigler as $lig):$fiksturUrl=$lig['tur']==='bireysel'?'/admin/bireysel-fikstur.php?lig_id=':(string)'/admin/lig-fikstur.php?lig_id=';?><div class="lig-fikstur-satir"><a href="<?= BASE_URL.$fiksturUrl.(int)$lig['id'] ?>"><strong><?= e($lig['lig_adi']) ?> Fikstürü</strong><small><?= $lig['tur']==='takim'?'Takım Ligi':'Bireysel Lig' ?></small></a><a class="btn btn-sm" href="<?= BASE_URL.$fiksturUrl.(int)$lig['id'] ?>">Düzenle</a></div><?php endforeach;?></section>
<?php $admin_baslik='Gruplar ve Fikstür';$admin_aktif='gruplar';$admin_geri_url=BASE_URL.'/admin/ligler.php';$admin_geri_ad='Ligler ve Sezon';$admin_icerik=ob_get_clean();require __DIR__.'/partials/layout.php';?>
