<?php
require_once __DIR__.'/../config/config.php';require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/functions.php';zorunlu_rol('admin');
$islem=$_GET['islem']??$_POST['islem']??'liste';$id=(int)($_GET['id']??$_POST['id']??0);
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!csrf_check($_POST['csrf']??'')){flash_set('hata','Güvenlik doğrulaması başarısız.');redirect(BASE_URL.'/admin/yoneticiler.php');}
    $ad=trim($_POST['ad_soyad']??'');$email=trim($_POST['email']??'');$kadi=trim($_POST['kullanici_adi']??'');$sifre=$_POST['sifre']??'';$aktif=isset($_POST['aktif'])?1:0;
    try{if($ad===''||$email===''||$kadi==='')throw new RuntimeException('Ad soyad, e-posta ve kullanıcı adı zorunludur.');$kontrol=$pdo->prepare('SELECT id FROM users WHERE (kullanici_adi=? OR email=?) AND id<>?');$kontrol->execute([$kadi,$email,$id]);if($kontrol->fetch())throw new RuntimeException('Kullanıcı adı veya e-posta kullanımda.');if($islem==='ekle'){if(strlen($sifre)<8)throw new RuntimeException('Şifre en az 8 karakter olmalıdır.');$pdo->prepare("INSERT INTO users(kullanici_adi,email,sifre,rol,ad_soyad,aktif) VALUES(?,?,?,'yonetici',?,?)")->execute([$kadi,$email,sifre_hash($sifre),$ad,$aktif]);flash_set('basari','Sınırlı yönetici eklendi.');}else{$pdo->prepare("UPDATE users SET kullanici_adi=?,email=?,ad_soyad=?,aktif=? WHERE id=? AND rol='yonetici'")->execute([$kadi,$email,$ad,$aktif,$id]);if($sifre!=='')$pdo->prepare("UPDATE users SET sifre=? WHERE id=? AND rol='yonetici'")->execute([sifre_hash($sifre),$id]);flash_set('basari','Yönetici güncellendi.');}}
    catch(Throwable $e){flash_set('hata',$e->getMessage());}redirect(BASE_URL.'/admin/yoneticiler.php');
}
$duzenlenen=null;if($islem==='duzenle'&&$id){$q=$pdo->prepare("SELECT * FROM users WHERE id=? AND rol='yonetici'");$q->execute([$id]);$duzenlenen=$q->fetch();if(!$duzenlenen)redirect(BASE_URL.'/admin/yoneticiler.php');}$liste=$pdo->query("SELECT * FROM users WHERE rol='yonetici' ORDER BY created_at DESC")->fetchAll();ob_start();?>
<?php if(in_array($islem,['ekle','duzenle'],true)): ?><form method="post" class="form"><?= csrf_field() ?><input type="hidden" name="islem" value="<?= e($islem) ?>"><?php if($duzenlenen): ?><input type="hidden" name="id" value="<?= (int)$duzenlenen['id'] ?>"><?php endif; ?><p class="muted">Bu rol yalnızca Organizasyon Yönetimi ve Katılımcılar alanlarına erişir.</p><div class="grid-2"><label>Ad Soyad *<input name="ad_soyad" required value="<?= e($duzenlenen['ad_soyad']??'') ?>"></label><label>E-posta *<input type="email" name="email" required value="<?= e($duzenlenen['email']??'') ?>"></label></div><div class="grid-2"><label>Kullanıcı Adı *<input name="kullanici_adi" required value="<?= e($duzenlenen['kullanici_adi']??'') ?>"></label><label>Şifre <?= $duzenlenen?'(boşsa değişmez)':'*' ?><input type="password" name="sifre" <?= $duzenlenen?'':'required' ?>></label></div><label class="check-line"><input type="checkbox" name="aktif" value="1" <?= (!$duzenlenen||$duzenlenen['aktif'])?'checked':'' ?>> Giriş yapabilir</label><div class="form-actions"><button class="btn btn-primary"><?= $duzenlenen?'Güncelle':'Yönetici Ekle' ?></button><a class="btn btn-outline" href="<?= BASE_URL ?>/admin/yoneticiler.php">İptal</a></div></form><?php else: ?><div class="toolbar"><a class="btn btn-primary" href="?islem=ekle">+ Yeni Yönetici</a></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Ad Soyad</th><th>Kullanıcı Adı</th><th>E-posta</th><th>Durum</th><th></th></tr></thead><tbody><?php foreach($liste as $yonetici): ?><tr><td><?= e($yonetici['ad_soyad']) ?></td><td><?= e($yonetici['kullanici_adi']) ?></td><td><?= e($yonetici['email']) ?></td><td><?= $yonetici['aktif']?'Aktif':'Pasif' ?></td><td><a class="btn btn-sm" href="?islem=duzenle&id=<?= (int)$yonetici['id'] ?>">Düzenle</a></td></tr><?php endforeach; ?><?php if(!$liste): ?><tr><td colspan="5" class="muted">Henüz sınırlı yönetici oluşturulmadı.</td></tr><?php endif; ?></tbody></table></div><?php endif; ?>
<?php $admin_baslik='Yöneticiler';$admin_aktif='yoneticiler';$admin_icerik=ob_get_clean();require __DIR__.'/partials/layout.php'; ?>
