<?php
require_once __DIR__.'/config/config.php';
require_once __DIR__.'/config/database.php';
require_once __DIR__.'/includes/functions.php';
$sayfa_baslik='Sezon Arşivi'; $aktif='ligler';
$sezonlar=$pdo->query("SELECT * FROM sezonlar WHERE durum='resmilesti' ORDER BY sezon_adi DESC")->fetchAll();
$sezonId=(int)($_GET['sezon_id']??($sezonlar[0]['id']??0));
$ligler=[]; $gruplar=[]; $sonuclar=[]; $ligId=(int)($_GET['lig_id']??0); $grupId=(int)($_GET['grup_id']??0); $seciliLig=null;
if($sezonId){$q=$pdo->prepare('SELECT id,lig_adi,tur FROM ligler WHERE sezon_id=? ORDER BY lig_adi');$q->execute([$sezonId]);$ligler=$q->fetchAll();foreach($ligler as $l)if((int)$l['id']===$ligId)$seciliLig=$l;if(!$seciliLig && $ligler){$seciliLig=$ligler[0];$ligId=(int)$seciliLig['id'];}}
if($ligId){$q=$pdo->prepare('SELECT id,grup_adi FROM gruplar WHERE lig_id=? ORDER BY grup_adi');$q->execute([$ligId]);$gruplar=$q->fetchAll();$gecerliGrup=false;foreach($gruplar as $g)if((int)$g['id']===$grupId)$gecerliGrup=true;if(!$gecerliGrup && $gruplar)$grupId=(int)$gruplar[0]['id'];}
if($sezonId && $ligId && $grupId && $seciliLig){$q=$pdo->prepare('SELECT * FROM sezon_sonuclari WHERE sezon_id=? AND lig_id=? AND grup_id=? ORDER BY sira');$q->execute([$sezonId,$ligId,$grupId]);$sonuclar=$q->fetchAll();}
require __DIR__.'/includes/header.php'; ?>
<main class="content"><section class="page-hero"><span class="eyebrow">RESMÎ KAYITLAR</span><h1>Sezon Arşivi</h1><p>Resmileştirilen sezonların puan tablolarını Sezon → Lig → Grup sırasıyla inceleyin.</p></section>
<?php if(!$sezonlar): ?><div class="card"><h2>Henüz resmileştirilmiş sezon yok</h2><p>Sezon sonuçları, yönetim panelinden sezon kapanışı yapıldığında burada görünür.</p></div><?php else: ?><form method="get" class="card form"><div class="grid-3"><label>Sezon<select name="sezon_id" onchange="this.form.submit()"><?php foreach($sezonlar as $s): ?><option value="<?= (int)$s['id'] ?>" <?= (int)$s['id']===$sezonId?'selected':'' ?>><?= e($s['sezon_adi']) ?></option><?php endforeach; ?></select></label><label>Lig<select name="lig_id" onchange="this.form.submit()"><?php foreach($ligler as $l): ?><option value="<?= (int)$l['id'] ?>" <?= (int)$l['id']===$ligId?'selected':'' ?>><?= e($l['lig_adi']) ?></option><?php endforeach; ?></select></label><label>Grup<select name="grup_id" onchange="this.form.submit()"><?php foreach($gruplar as $g): ?><option value="<?= (int)$g['id'] ?>" <?= (int)$g['id']===$grupId?'selected':'' ?>><?= e($g['grup_adi']) ?></option><?php endforeach; ?></select></label></div><noscript><button class="btn btn-primary">Sonuçları Göster</button></noscript></form><section class="card"><div class="card-head"><h2><?= $seciliLig?e($seciliLig['lig_adi']).' · ':'' ?><?= $grupId?e(current(array_filter($gruplar,fn($g)=>(int)$g['id']===$grupId))['grup_adi']??''):'' ?></h2><span class="badge">Resmî sonuç</span></div><?php if(!$sonuclar): ?><p>Bu filtre için kaydedilmiş sonuç bulunmuyor.</p><?php else: ?><div class="table-wrap"><table class="data-table"><thead><tr><th>#</th><th><?= $seciliLig['tur']==='bireysel'?'Sporcu':'Takım' ?></th><?php if($seciliLig['tur']==='takim'): ?><th>O</th><th>G</th><th>M</th><th>Set</th><?php endif; ?><th>Puan</th></tr></thead><tbody><?php foreach($sonuclar as $s): ?><tr><td><?= (int)$s['sira'] ?></td><td><strong><?= e($s['ad']) ?></strong></td><?php if($seciliLig['tur']==='takim'): ?><td><?= (int)$s['oynanan'] ?></td><td><?= (int)$s['galibiyet'] ?></td><td><?= (int)$s['maglubiyet'] ?></td><td><?= (int)$s['toplam_set'] ?></td><?php endif; ?><td><strong><?= (int)$s['toplam_puan'] ?></strong></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></section><?php endif; ?></main>
<?php require __DIR__.'/includes/footer.php'; ?>
