<?php
require_once __DIR__ . '/config/config.php'; require_once __DIR__ . '/config/database.php'; require_once __DIR__ . '/includes/functions.php';
zorunlu_rol('uye','admin','hakem','yetkili','sporcu');
$sayfa_baslik='Favorilerim'; $aktif='favoriler'; require_once __DIR__ . '/includes/header.php'; $uid=kullanici_bilgi()['id'];
$st=$pdo->prepare("SELECT f.hedef_id,t.takim_adi,t.sehir FROM favoriler f JOIN takimlar t ON t.id=f.hedef_id WHERE f.user_id=? AND f.tur='takim' ORDER BY f.created_at DESC"); $st->execute([$uid]); $takimlar=$st->fetchAll();
$st=$pdo->prepare("SELECT f.hedef_id,s.ad,s.soyad,t.takim_adi FROM favoriler f JOIN sporcular s ON s.id=f.hedef_id LEFT JOIN takimlar t ON t.id=s.takim_id WHERE f.user_id=? AND f.tur='sporcu' ORDER BY f.created_at DESC"); $st->execute([$uid]); $sporcular=$st->fetchAll();
?>
<main class="main-content"><section class="page-heading"><span>Takip merkezi</span><h1>Favorilerim</h1><p>Takip ettiğiniz takım ve sporculara buradan hızlıca ulaşın.</p></section><div class="favorite-grid"><section class="card"><div class="card-head"><h2>🏹 Takımlar</h2></div><?php if(!$takimlar): ?><p class="muted">Henüz takım takip etmiyorsunuz.</p><?php else: foreach($takimlar as $t): ?><p class="favorite-row"><a href="<?= BASE_URL ?>/takim.php?id=<?= (int)$t['hedef_id'] ?>"><strong><?= e($t['takim_adi']) ?></strong><small><?= e($t['sehir'] ?: 'Takım') ?></small></a></p><?php endforeach; endif; ?></section><section class="card"><div class="card-head"><h2>🎯 Sporcular</h2></div><?php if(!$sporcular): ?><p class="muted">Henüz sporcu takip etmiyorsunuz.</p><?php else: foreach($sporcular as $s): ?><p class="favorite-row"><a href="<?= BASE_URL ?>/sporcu.php?id=<?= (int)$s['hedef_id'] ?>"><strong><?= e($s['ad'].' '.$s['soyad']) ?></strong><small><?= e($s['takim_adi'] ?: 'Sporcu') ?></small></a></p><?php endforeach; endif; ?></section></div></main>
<?php require_once __DIR__ . '/includes/sidebar.php'; require_once __DIR__ . '/includes/footer.php'; ?>
