<?php
require_once __DIR__.'/config/config.php';require_once __DIR__.'/config/database.php';require_once __DIR__.'/includes/functions.php';
$id=(int)($_GET['id']??0);$st=$pdo->prepare('SELECT * FROM ligler WHERE id=? AND aktif=1');$st->execute([$id]);$lig=$st->fetch();if(!$lig)redirect(BASE_URL.'/ligler.php');
$st=$pdo->prepare('SELECT * FROM gruplar WHERE lig_id=? ORDER BY grup_adi');$st->execute([$id]);$gruplar=$st->fetchAll();$grupId=(int)($_GET['grup_id']??($gruplar[0]['id']??0));$gecerli=array_map(fn($g)=>(int)$g['id'],$gruplar);if(!in_array($grupId,$gecerli,true))$grupId=$gecerli[0]??0;
if($lig['tur']==='bireysel'){$st=$pdo->prepare('SELECT s.*,k.toplam_puan,k.atis_sayisi,t.takim_adi FROM bireysel_lig_kayitlari k JOIN sporcular s ON s.id=k.sporcu_id LEFT JOIN takimlar t ON t.id=s.takim_id WHERE k.lig_id=? AND k.grup_id=? ORDER BY k.toplam_puan DESC,k.atis_sayisi ASC,s.ad,s.soyad');$st->execute([$id,$grupId]);$liste=$st->fetchAll();}else{$st=$pdo->prepare('SELECT * FROM takimlar WHERE grup_id=? ORDER BY toplam_set DESC,toplam_puan DESC,takim_adi');$st->execute([$grupId]);$liste=$st->fetchAll();}
$sayfa_baslik=$lig['lig_adi'];$aktif='ligler';require __DIR__.'/includes/header.php';
?>
<main class="main-content"><section class="page-heading"><span class="eyebrow"><?= $lig['tur']==='bireysel'?'BİREYSEL BÖLGE LİGLERİ':'GELENEKSEL OKÇULUK TAKIM LİGLERİ' ?></span><h1><?= e($lig['lig_adi']) ?></h1><p><?= e($lig['aciklama']?:'Lig grupları ve güncel puan durumunu takip edin.') ?></p></section>
<form method="get" class="card form"><input type="hidden" name="id" value="<?= $id ?>"><label>Grup<select name="grup_id" onchange="this.form.submit()"><?php foreach($gruplar as $gr):?><option value="<?= (int)$gr['id'] ?>" <?= $grupId===(int)$gr['id']?'selected':'' ?>><?= e($gr['grup_adi']) ?></option><?php endforeach;?></select></label><noscript><div class="form-actions"><button class="btn btn-primary">Göster</button></div></noscript></form>
<section class="card table-card"><?php if(!$liste):?><p class="empty-state">Bu grupta henüz listelenecek kayıt bulunmuyor.</p><?php elseif($lig['tur']==='bireysel'):?><div class="table-wrap"><table class="data-table"><thead><tr><th>#</th><th>Sporcu</th><th>Kategori</th><th>Takım</th><th>Grup</th><th>Puan</th><th>Atış</th><th>Ort.</th></tr></thead><tbody><?php foreach($liste as $i=>$x):$ort=$x['atis_sayisi']?number_format($x['toplam_puan']/$x['atis_sayisi'],2,',','.'): '0,00';?><tr><td class="rank"><?= $i+1 ?></td><td><a href="<?= BASE_URL ?>/sporcu.php?id=<?= (int)$x['id'] ?>"><strong><?= e($x['ad'].' '.$x['soyad']) ?></strong></a></td><td><?= e($x['kategori']?:'-') ?></td><td><?php if($x['takim_id']):?><a href="<?= BASE_URL ?>/takim.php?id=<?= (int)$x['takim_id'] ?>"><?= e($x['takim_adi']) ?></a><?php else:?>Bağımsız<?php endif;?></td><td><?= e($gruplar[array_search($grupId,array_column($gruplar,'id'))]['grup_adi']??'-') ?></td><td><?= (int)$x['toplam_puan'] ?></td><td><?= (int)$x['atis_sayisi'] ?></td><td><?= $ort ?></td></tr><?php endforeach;?></tbody></table></div><?php else:?><div class="table-wrap"><table class="data-table"><thead><tr><th>#</th><th>Takım</th><th>Grup</th><th>Şehir</th><th>Galibiyet</th><th>Mağlubiyet</th><th>Set Puanı</th><th>Atış Puanı</th></tr></thead><tbody><?php foreach($liste as $i=>$x):?><tr><td class="rank"><?= $i+1 ?></td><td><a href="<?= BASE_URL ?>/takim.php?id=<?= (int)$x['id'] ?>"><strong><?= e($x['takim_adi']) ?></strong></a></td><td><?= e($gruplar[array_search($grupId,array_column($gruplar,'id'))]['grup_adi']??'-') ?></td><td><?= e($x['sehir']?:'-') ?></td><td><?= (int)$x['kazanilan_mac'] ?></td><td><?= (int)$x['kaybedilen_mac'] ?></td><td><strong><?= (int)$x['toplam_set'] ?></strong></td><td><?= (int)$x['toplam_puan'] ?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section></main>
<?php require __DIR__.'/includes/sidebar.php';require __DIR__.'/includes/footer.php'; ?>
