<?php
require_once __DIR__.'/config/config.php';require_once __DIR__.'/config/database.php';require_once __DIR__.'/includes/functions.php';
$id=(int)($_GET['id']??0);$q=$pdo->prepare("SELECT m.*,a.takim_adi ev,b.takim_adi dep,g.grup_adi,h.ad ha,h.soyad hs FROM maclar m JOIN takimlar a ON a.id=m.ev_sahibi_id JOIN takimlar b ON b.id=m.deplasman_id JOIN gruplar g ON g.id=m.grup_id LEFT JOIN hakemler h ON h.id=m.hakem_id WHERE m.id=?");$q->execute([$id]);$m=$q->fetch();if(!$m)exit('Maç bulunamadı.');
$q=$pdo->prepare('SELECT * FROM mac_setleri WHERE mac_id=? ORDER BY set_no');$q->execute([$id]);$setler=$q->fetchAll();$q=$pdo->prepare("SELECT x.*,s.ad,s.soyad FROM sporcu_set_atislari x JOIN sporcular s ON s.id=x.sporcu_id WHERE x.mac_id=? ORDER BY x.set_no,x.takim_id,s.ad");$q->execute([$id]);$atis=[];foreach($q as $x)$atis[$x['set_no']][$x['takim_id']][]=$x;$q=$pdo->prepare("SELECT * FROM esitlik_bozma_atislari WHERE kaynak='lig' AND mac_id=? ORDER BY set_no,tur_no");$q->execute([$id]);$eb=$q->fetchAll();$sayfa_baslik=$m['ev'].' - '.$m['dep'];$aktif='sonuclar';require __DIR__.'/includes/header.php';
?>
<main class="main-content"><section class="page-heading mac-ozet"><span>KARŞILAŞMA SONUCU</span><h1><a href="<?= BASE_URL ?>/takim.php?id=<?= (int)$m['ev_sahibi_id'] ?>"><?= e($m['ev']) ?></a><b><?= (int)$m['ev_sahibi_set'] ?> - <?= (int)$m['deplasman_set'] ?></b><a href="<?= BASE_URL ?>/takim.php?id=<?= (int)$m['deplasman_id'] ?>"><?= e($m['dep']) ?></a></h1><p><?= e($m['grup_adi']) ?> · Hakem: <?= e(trim($m['ha'].' '.$m['hs'])?:'Atanmadı') ?></p></section>
<section class="mac-skor-foyu"><?php if(!$setler): ?><div class="card muted">Bu karşılaşma için henüz set skoru girilmedi.</div><?php endif; ?><?php foreach($setler as $st): $evAtis=$atis[$st['set_no']][$m['ev_sahibi_id']]??[];$depAtis=$atis[$st['set_no']][$m['deplasman_id']]??[];$satirSayisi=max(count($evAtis),count($depAtis)); ?><div class="set-foyu"><div class="set-foyu-baslik"><span><?= (int)$st['set_no'] ?>. Set</span><strong><?= (int)$st['ev_sahibi_set_puani'] ?> - <?= (int)$st['deplasman_set_puani'] ?></strong></div><div class="table-wrap"><table class="set-skor-tablosu"><thead><tr><th><?= e($m['ev']) ?></th><th>Puan</th><th><?= e($m['dep']) ?></th><th>Puan</th></tr></thead><tbody><?php for($i=0;$i<$satirSayisi;$i++): $ev=$evAtis[$i]??null;$dep=$depAtis[$i]??null; ?><tr><td><?php if($ev): ?><a href="<?= BASE_URL ?>/sporcu.php?id=<?= (int)$ev['sporcu_id'] ?>"><?= e($ev['ad'].' '.$ev['soyad']) ?></a><?php else: ?>—<?php endif; ?></td><td class="set-puan"><?= $ev?(int)$ev['set_toplam']:'—' ?></td><td><?php if($dep): ?><a href="<?= BASE_URL ?>/sporcu.php?id=<?= (int)$dep['sporcu_id'] ?>"><?= e($dep['ad'].' '.$dep['soyad']) ?></a><?php else: ?>—<?php endif; ?></td><td class="set-puan"><?= $dep?(int)$dep['set_toplam']:'—' ?></td></tr><?php endfor; ?></tbody></table></div></div><?php endforeach; ?></section>
<?php if($eb): ?><section class="esitlik-ozet"><strong>Eşitlik bozma</strong><?php foreach($eb as $x): ?><span><?= (int)$x['set_no'] ?>. set / <?= (int)$x['tur_no'] ?>. tur: <b><?= (int)$x['ev_puan'] ?> - <?= (int)$x['dep_puan'] ?></b></span><?php endforeach; ?></section><?php endif; ?></main>
<?php require __DIR__.'/includes/sidebar.php';require __DIR__.'/includes/footer.php'; ?>
