<?php
require_once __DIR__.'/config/config.php';require_once __DIR__.'/config/database.php';require_once __DIR__.'/includes/functions.php';
$ligler=$pdo->query('SELECT id,lig_adi,tur FROM ligler WHERE aktif=1 ORDER BY lig_adi')->fetchAll();$turnuvalar=$pdo->query('SELECT id,turnuva_adi,tur FROM turnuvalar ORDER BY turnuva_adi')->fetchAll();
$secenekler=['tum'=>['tip'=>'tum','id'=>0,'tur'=>null]];foreach($ligler as $x)$secenekler['lig:'.$x['id']]=['tip'=>'lig','id'=>(int)$x['id'],'tur'=>$x['tur']];foreach($turnuvalar as $x)$secenekler['turnuva:'.$x['id']]=['tip'=>'turnuva','id'=>(int)$x['id'],'tur'=>$x['tur']];
$kaynak=$_GET['kaynak']??'tum';if(!isset($secenekler[$kaynak]))$kaynak='tum';$secili=$secenekler[$kaynak];$gruplar=[];$grupId=0;$takimlar=[];$takimId=0;
if($secili['tip']==='lig'){$st=$pdo->prepare('SELECT id,grup_adi FROM gruplar WHERE lig_id=? ORDER BY grup_adi');$st->execute([$secili['id']]);$gruplar=$st->fetchAll();$gecerli=array_map(fn($g)=>(int)$g['id'],$gruplar);$grupId=(int)($_GET['grup']??0);if($grupId&&!in_array($grupId,$gecerli,true))$grupId=0;}
if($secili['tip']==='lig'&&$secili['tur']==='takim'){$st=$pdo->prepare('SELECT t.id,t.takim_adi FROM takimlar t JOIN gruplar g ON g.id=t.grup_id WHERE g.lig_id=? AND (?=0 OR g.id=?) ORDER BY t.takim_adi');$st->execute([$secili['id'],$grupId,$grupId]);$takimlar=$st->fetchAll();}
$gecerliTakim=array_map(fn($t)=>(int)$t['id'],$takimlar);$takimId=(int)($_GET['takim']??0);if($takimId&&!in_array($takimId,$gecerliTakim,true))$takimId=0;
$sql="SELECT s.*,t.takim_adi,g.grup_adi,l.lig_adi FROM sporcular s LEFT JOIN takimlar t ON t.id=s.takim_id LEFT JOIN gruplar g ON g.id=t.grup_id LEFT JOIN ligler l ON l.id=g.lig_id WHERE 1=1";$p=[];
if($secili['tip']==='lig'){
    if($secili['tur']==='takim'){$sql.=' AND l.id=?';$p[]=$secili['id'];if($grupId){$sql.=' AND g.id=?';$p[]=$grupId;}if($takimId){$sql.=' AND s.takim_id=?';$p[]=$takimId;}}
    else {$sql.=' AND EXISTS(SELECT 1 FROM bireysel_lig_kayitlari k WHERE k.lig_id=? AND k.sporcu_id=s.id';$p[]=$secili['id'];if($grupId){$sql.=' AND k.grup_id=?';$p[]=$grupId;}$sql.=')';}
} elseif($secili['tip']==='turnuva'){
    if($secili['tur']==='bireysel'){$sql.=' AND EXISTS(SELECT 1 FROM turnuva_katilimcilari k WHERE k.turnuva_id=? AND k.hedef_id=s.id)';$p[]=$secili['id'];}
    else {$sql.=' AND EXISTS(SELECT 1 FROM turnuva_katilimcilari k WHERE k.turnuva_id=? AND k.hedef_id=s.takim_id)';$p[]=$secili['id'];}
}
$sql.=' ORDER BY s.ad,s.soyad';$st=$pdo->prepare($sql);$st->execute($p);$sporcular=$st->fetchAll();
$sayfa_baslik='Sporcular';$aktif='sporcular';require __DIR__.'/includes/header.php';
?>
<main class="main-content"><section class="page-heading"><span class="eyebrow">SPORCULAR</span><h1>Sporcular</h1><p>Lig veya turnuva, grup ve takım seçerek sporcuları filtreleyebilirsiniz.</p></section>
<form method="get" class="card form"><div class="grid-3"><label>Lig / Turnuva<select name="kaynak" onchange="this.form.submit()"><option value="tum" <?= $kaynak==='tum'?'selected':'' ?>>Tümü</option><?php if($ligler):?><optgroup label="Ligler"><?php foreach($ligler as $x):?><option value="lig:<?= (int)$x['id'] ?>" <?= $kaynak==='lig:'.$x['id']?'selected':'' ?>><?= e($x['lig_adi']) ?><?= $x['tur']==='bireysel'?' · Bireysel':'' ?></option><?php endforeach;?></optgroup><?php endif;?><?php if($turnuvalar):?><optgroup label="Turnuvalar"><?php foreach($turnuvalar as $x):?><option value="turnuva:<?= (int)$x['id'] ?>" <?= $kaynak==='turnuva:'.$x['id']?'selected':'' ?>><?= e($x['turnuva_adi']) ?><?= $x['tur']==='bireysel'?' · Bireysel':'' ?></option><?php endforeach;?></optgroup><?php endif;?></select></label>
<label>Grup<?php if($secili['tip']==='lig'):?><select name="grup" onchange="this.form.submit()"><option value="0">Tüm Gruplar</option><?php foreach($gruplar as $g):?><option value="<?= (int)$g['id'] ?>" <?= $grupId===(int)$g['id']?'selected':'' ?>><?= e($g['grup_adi']) ?></option><?php endforeach;?></select><?php else:?><input value="Tüm Gruplar" disabled><?php endif;?></label>
<label>Takım<?php if($secili['tip']==='lig'&&$secili['tur']==='takim'):?><select name="takim" onchange="this.form.submit()"><option value="0">Tüm Takımlar</option><?php foreach($takimlar as $t):?><option value="<?= (int)$t['id'] ?>" <?= $takimId===(int)$t['id']?'selected':'' ?>><?= e($t['takim_adi']) ?></option><?php endforeach;?></select><?php else:?><input value="Tüm Takımlar" disabled><?php endif;?></label></div><noscript><div class="form-actions"><button class="btn btn-primary">Filtrele</button></div></noscript></form>
<section class="card table-card"><?php if(!$sporcular):?><p class="empty-state">Seçilen filtreye uygun sporcu bulunmuyor.</p><?php else:?><div class="table-wrap"><table class="data-table"><thead><tr><th>Sporcu</th><th>Kategori</th><th>Takım</th><th>Lig</th><th>Grup</th><th>Puan</th><th>Atış</th><th>Ort.</th></tr></thead><tbody><?php foreach($sporcular as $s):$ort=$s['atis_sayisi']?(number_format($s['toplam_puan']/$s['atis_sayisi'],2,',','.')):'0,00';?><tr><td><a href="<?= BASE_URL ?>/sporcu.php?id=<?= (int)$s['id'] ?>"><strong><?= e($s['ad'].' '.$s['soyad']) ?></strong></a></td><td><?= e($s['kategori']?:'-') ?></td><td><?php if($s['takim_id']):?><a href="<?= BASE_URL ?>/takim.php?id=<?= (int)$s['takim_id'] ?>"><?= e($s['takim_adi']) ?></a><?php else:?>Bağımsız<?php endif;?></td><td><?= e($s['lig_adi']?:'-') ?></td><td><?= e($s['grup_adi']?:'-') ?></td><td><?= (int)$s['toplam_puan'] ?></td><td><?= (int)$s['atis_sayisi'] ?></td><td><?= $ort ?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section></main>
<?php require __DIR__.'/includes/sidebar.php';require __DIR__.'/includes/footer.php'; ?>
