<?php
require_once __DIR__.'/config/config.php';require_once __DIR__.'/config/database.php';require_once __DIR__.'/includes/functions.php';
$ligler=$pdo->query("SELECT id,lig_adi FROM ligler WHERE aktif=1 AND tur='takim' ORDER BY lig_adi")->fetchAll();$turnuvalar=$pdo->query("SELECT id,turnuva_adi FROM turnuvalar WHERE tur='takim' ORDER BY turnuva_adi")->fetchAll();
$secenekler=['tum'=>['tip'=>'tum','id'=>0,'ad'=>'Tümü']];foreach($ligler as $x)$secenekler['lig:'.$x['id']]=['tip'=>'lig','id'=>(int)$x['id'],'ad'=>$x['lig_adi']];foreach($turnuvalar as $x)$secenekler['turnuva:'.$x['id']]=['tip'=>'turnuva','id'=>(int)$x['id'],'ad'=>$x['turnuva_adi']];
$kaynak=$_GET['kaynak']??'tum';if(!isset($secenekler[$kaynak]))$kaynak='tum';$secili=$secenekler[$kaynak];$gruplar=[];$grupId=0;
if($secili['tip']==='lig'){$st=$pdo->prepare('SELECT id,grup_adi FROM gruplar WHERE lig_id=? ORDER BY grup_adi');$st->execute([$secili['id']]);$gruplar=$st->fetchAll();$gecerli=array_map(fn($g)=>(int)$g['id'],$gruplar);$grupId=(int)($_GET['grup']??0);if($grupId&&!in_array($grupId,$gecerli,true))$grupId=0;}
$sql="SELECT t.*,g.grup_adi,l.lig_adi FROM takimlar t JOIN gruplar g ON g.id=t.grup_id JOIN ligler l ON l.id=g.lig_id WHERE 1=1";$p=[];
if($secili['tip']==='lig'){$sql.=' AND l.id=?';$p[]=$secili['id'];if($grupId){$sql.=' AND g.id=?';$p[]=$grupId;}}
elseif($secili['tip']==='turnuva'){$sql.=' AND EXISTS(SELECT 1 FROM turnuva_katilimcilari k WHERE k.turnuva_id=? AND k.hedef_id=t.id)';$p[]=$secili['id'];}
$sql.=' ORDER BY t.takim_adi';$st=$pdo->prepare($sql);$st->execute($p);$takimlar=$st->fetchAll();
$sayfa_baslik='Takımlar';$aktif='takimlar';require __DIR__.'/includes/header.php';
?>
<main class="main-content"><section class="page-heading"><span class="eyebrow">KULÜPLER</span><h1>Takımlar</h1><p>Lig veya turnuva, ardından grup seçerek takımları filtreleyebilirsiniz.</p></section>
<form method="get" class="card form"><div class="grid-2"><label>Lig / Turnuva<select name="kaynak" onchange="this.form.submit()"><option value="tum" <?= $kaynak==='tum'?'selected':'' ?>>Tümü</option><?php if($ligler):?><optgroup label="Ligler"><?php foreach($ligler as $x):?><option value="lig:<?= (int)$x['id'] ?>" <?= $kaynak==='lig:'.$x['id']?'selected':'' ?>><?= e($x['lig_adi']) ?></option><?php endforeach;?></optgroup><?php endif;?><?php if($turnuvalar):?><optgroup label="Turnuvalar"><?php foreach($turnuvalar as $x):?><option value="turnuva:<?= (int)$x['id'] ?>" <?= $kaynak==='turnuva:'.$x['id']?'selected':'' ?>><?= e($x['turnuva_adi']) ?></option><?php endforeach;?></optgroup><?php endif;?></select></label>
<label>Grup<?php if($secili['tip']==='lig'):?><select name="grup" onchange="this.form.submit()"><option value="0">Tüm Gruplar</option><?php foreach($gruplar as $g):?><option value="<?= (int)$g['id'] ?>" <?= $grupId===(int)$g['id']?'selected':'' ?>><?= e($g['grup_adi']) ?></option><?php endforeach;?></select><?php else:?><input value="Tüm Gruplar" disabled><?php endif;?></label>
</div><noscript><div class="form-actions"><button class="btn btn-primary">Filtrele</button></div></noscript></form>
<section class="card table-card"><?php if(!$takimlar):?><p class="empty-state">Seçilen filtreye uygun takım bulunmuyor.</p><?php else:?><div class="table-wrap"><table class="data-table"><thead><tr><th>Takım</th><th>Lig</th><th>Grup</th><th>Şehir</th><th>Galibiyet</th><th>Mağlubiyet</th><th>Puan</th></tr></thead><tbody><?php foreach($takimlar as $t):?><tr><td><a href="<?= BASE_URL ?>/takim.php?id=<?= (int)$t['id'] ?>"><strong><?= e($t['takim_adi']) ?></strong></a></td><td><?= e($t['lig_adi']) ?></td><td><?= e($t['grup_adi']) ?></td><td><?= e($t['sehir']?:'-') ?></td><td><?= (int)$t['kazanilan_mac'] ?></td><td><?= (int)$t['kaybedilen_mac'] ?></td><td><?= (int)$t['toplam_puan'] ?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section></main>
<?php require __DIR__.'/includes/sidebar.php';require __DIR__.'/includes/footer.php'; ?>
