<?php
require_once __DIR__.'/../config/config.php';require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/functions.php';zorunlu_rol('admin');
$ligId=(int)($_GET['lig_id']??$_POST['lig_id']??0);$st=$pdo->prepare("SELECT * FROM ligler WHERE id=? AND tur='bireysel'");$st->execute([$ligId]);$lig=$st->fetch();if(!$lig){flash_set('hata','Bireysel Bölge Ligleri kaydı bulunamadı.');redirect(BASE_URL.'/admin/ligler.php');}
$grupSt=$pdo->prepare('SELECT * FROM gruplar WHERE lig_id=? ORDER BY bolge_adi,kategori_adi,grup_adi');$grupSt->execute([$ligId]);$gruplar=$grupSt->fetchAll();$grupId=(int)($_GET['grup_id']??$_POST['grup_id']??($gruplar[0]['id']??0));$seciliGrup=null;foreach($gruplar as $g)if((int)$g['id']===$grupId)$seciliGrup=$g;if(!$seciliGrup){flash_set('hata','Grup bulunamadı.');redirect(BASE_URL.'/admin/bireysel-katilim.php?lig_id='.$ligId);}
$kategori=trim($seciliGrup['kategori_adi']??'');
if($_SERVER['REQUEST_METHOD']==='POST'){if(!csrf_check($_POST['csrf']??'')){flash_set('hata','Güvenlik doğrulaması başarısız.');}elseif($kategori===''){flash_set('hata','Bu grubun kategorisi tanımlı değil. Önce grubu düzenleyin.');}else{$izin=$pdo->prepare('SELECT id FROM sporcular WHERE TRIM(kategori)=TRIM(?)');$izin->execute([$kategori]);$izinli=array_flip(array_column($izin->fetchAll(),'id'));$secilen=array_unique(array_map('intval',$_POST['sporcular']??[]));if(array_diff($secilen,array_keys($izinli))){flash_set('hata','Yalnızca '.$kategori.' kategorisindeki sporcular kaydedilebilir.');}else{$pdo->prepare('DELETE FROM bireysel_lig_kayitlari WHERE lig_id=? AND grup_id=?')->execute([$ligId,$grupId]);$ins=$pdo->prepare('INSERT INTO bireysel_lig_kayitlari(lig_id,grup_id,sporcu_id) VALUES(?,?,?)');foreach($secilen as $sid)$ins->execute([$ligId,$grupId,$sid]);flash_set('basari','Sporcu kayıtları güncellendi.');}}redirect(BASE_URL.'/admin/bireysel-katilim.php?lig_id='.$ligId.'&grup_id='.$grupId);}
$sporcuSt=$pdo->prepare('SELECT s.id,s.ad,s.soyad,s.kategori,t.takim_adi FROM sporcular s LEFT JOIN takimlar t ON t.id=s.takim_id WHERE TRIM(s.kategori)=TRIM(?) ORDER BY s.ad,s.soyad');$sporcuSt->execute([$kategori]);$sporcular=$sporcuSt->fetchAll();$sec=$pdo->prepare('SELECT sporcu_id FROM bireysel_lig_kayitlari WHERE lig_id=? AND grup_id=?');$sec->execute([$ligId,$grupId]);$sec=array_flip(array_column($sec->fetchAll(),'sporcu_id'));ob_start();
?>
<div class="toolbar"><a class="btn" href="<?= BASE_URL ?>/admin/ligler.php">← Liglere dön</a></div><div class="card"><div class="card-head"><h2><?= e($lig['lig_adi']) ?> — sporcu kayıtları</h2><span class="badge"><?= e($kategori ?: 'Kategori tanımsız') ?></span></div><form method="get" class="toolbar"><input type="hidden" name="lig_id" value="<?= $ligId ?>"><select name="grup_id" onchange="this.form.submit()"><?php foreach($gruplar as $g):?><option value="<?= (int)$g['id'] ?>" <?= $grupId===(int)$g['id']?'selected':'' ?>><?= e($g['grup_adi']) ?></option><?php endforeach;?></select></form><form method="post" class="form"><?= csrf_field() ?><input type="hidden" name="lig_id" value="<?= $ligId ?>"><input type="hidden" name="grup_id" value="<?= $grupId ?>"><p class="muted">Bu gruba yalnızca <strong><?= e($kategori) ?></strong> kategorisindeki sporcular eklenebilir.</p><div class="katilim-listesi"><?php foreach($sporcular as $s):?><label class="katilim-satir"><input type="checkbox" name="sporcular[]" value="<?= (int)$s['id'] ?>" <?= isset($sec[$s['id']])?'checked':'' ?>><span><?= e($s['ad'].' '.$s['soyad']) ?></span><small><?= e($s['takim_adi']?:'Takımsız') ?> · <?= e($s['kategori']) ?></small></label><?php endforeach;?></div><div class="form-actions"><button class="btn btn-primary">Kayıtları kaydet</button></div></form></div>
<?php $admin_baslik='Bireysel Bölge Ligleri Katılımcıları';$admin_aktif='ligler';$admin_icerik=ob_get_clean();require __DIR__.'/partials/layout.php'; ?>
