<?php
require_once __DIR__.'/../config/config.php';require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/functions.php';zorunlu_rol('admin');
function turnuva_etiket($sira){$sira=(int)$sira-1;$etiket='';do{$etiket=chr(65+($sira%26)).$etiket;$sira=intdiv($sira,26)-1;}while($sira>=0);return $etiket;}
$id=(int)($_GET['id']??$_POST['turnuva_id']??0);
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!csrf_check($_POST['csrf']??'')){flash_set('hata','Güvenlik doğrulaması başarısız.');redirect(BASE_URL.'/admin/turnuvalar.php');}
 try{
  $islem=$_POST['islem']??'';
  if($islem==='turnuva_olustur'){
   $ad=trim($_POST['turnuva_adi']??'');$tur=$_POST['tur']??'takim';$kontenjan=(int)($_POST['kontenjan']??16);$sezonId=(int)($_POST['sezon_id']??0);
   if($ad===''||!in_array($tur,['takim','bireysel'],true)||!in_array($kontenjan,[16,32],true)||!$sezonId)throw new RuntimeException('Turnuva adı, türü, sezonu ve kontenjanı seçin.');
   $s=$pdo->prepare("SELECT sezon_adi FROM sezonlar WHERE id=? AND durum='aktif'");$s->execute([$sezonId]);if(!$s->fetchColumn())throw new RuntimeException('Yalnızca aktif sezona turnuva eklenebilir.');
   $pdo->prepare('INSERT INTO turnuvalar(turnuva_adi,tur,kontenjan,sezon_id,aciklama) VALUES(?,?,?,?,?)')->execute([$ad,$tur,$kontenjan,$sezonId,trim($_POST['aciklama']??'')]);$id=(int)$pdo->lastInsertId();flash_set('basari','Turnuva oluşturuldu. Katılımcıları yerleştirin.');
  }elseif($islem==='katilimcilari_kaydet'){
   $t=$pdo->prepare('SELECT * FROM turnuvalar WHERE id=?');$t->execute([$id]);$turnuva=$t->fetch();if(!$turnuva)throw new RuntimeException('Turnuva bulunamadı.');if($turnuva['durum']!=='taslak')throw new RuntimeException('Eşleşmesi oluşturulmuş turnuvanın katılımcıları değiştirilemez.');
   $hedefler=array_values(array_filter(array_map('intval',$_POST['katilimci']??[])));if(count($hedefler)!==(int)$turnuva['kontenjan']||count(array_unique($hedefler))!==count($hedefler))throw new RuntimeException('Kontenjan kadar farklı katılımcı seçmelisiniz.');
   $pdo->beginTransaction();$pdo->prepare('DELETE FROM turnuva_katilimcilari WHERE turnuva_id=?')->execute([$id]);$ins=$pdo->prepare('INSERT INTO turnuva_katilimcilari(turnuva_id,hedef_id,sira) VALUES(?,?,?)');foreach($hedefler as $sira=>$hedef)$ins->execute([$id,$hedef,$sira+1]);$pdo->commit();flash_set('basari','Katılımcılar kaydedildi.');
  }elseif($islem==='eslesme_olustur'){
   $t=$pdo->prepare('SELECT * FROM turnuvalar WHERE id=?');$t->execute([$id]);$turnuva=$t->fetch();$k=$pdo->prepare('SELECT id,hedef_id FROM turnuva_katilimcilari WHERE turnuva_id=? ORDER BY sira');$k->execute([$id]);$katilimcilar=$k->fetchAll();if(!$turnuva||count($katilimcilar)!==(int)$turnuva['kontenjan'])throw new RuntimeException('Önce kontenjan kadar katılımcı kaydedin.');
   $pdo->beginTransaction();$pdo->prepare('DELETE FROM turnuva_maclari WHERE turnuva_id=?')->execute([$id]);$pdo->prepare('DELETE FROM turnuva_eslesmeleri WHERE turnuva_id=?')->execute([$id]);$esIns=$pdo->prepare('INSERT INTO turnuva_eslesmeleri(turnuva_id,tur_no,eslesme_no,katilimci1_id,katilimci2_id) VALUES(?,?,?,?,?)');$macIns=$pdo->prepare('INSERT INTO turnuva_maclari(turnuva_id,eslesme_id,katilimci1_id,katilimci2_id,tur_no) VALUES(?,?,?,?,?)');$no=1;for($i=0;$i<count($katilimcilar);$i+=4){foreach([[$i,$i+2],[$i+1,$i+3]] as [$a,$b]){$esIns->execute([$id,1,$no++,$katilimcilar[$a]['id'],$katilimcilar[$b]['id']]);$macIns->execute([$id,$pdo->lastInsertId(),$katilimcilar[$a]['hedef_id'],$katilimcilar[$b]['hedef_id'],1]);}}
   $turSayisi=(int)round(log((int)$turnuva['kontenjan'],2));for($tur=2;$tur<=$turSayisi;$tur++){for($sira=1;$sira<=(int)$turnuva['kontenjan']/(2**$tur);$sira++){$esIns->execute([$id,$tur,$sira,null,null]);$macIns->execute([$id,$pdo->lastInsertId(),null,null,$tur]);}}
   $pdo->prepare("UPDATE turnuvalar SET durum='eslesme_hazir' WHERE id=?")->execute([$id]);$pdo->commit();flash_set('basari','Finale kadar turnuva ağacı oluşturuldu. Kazananlar üst tura otomatik yerleşecek.');
  }
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash_set('hata',$e->getMessage());}
 redirect(BASE_URL.'/admin/turnuvalar.php'.($id?'?id='.$id:''));
}
$sezonlar=$pdo->query("SELECT * FROM sezonlar WHERE durum='aktif' ORDER BY sezon_adi DESC")->fetchAll();$t=null;$katilimcilar=[];$adaylar=[];$eslesmeler=[];
if($id){$s=$pdo->prepare('SELECT t.*,s.sezon_adi FROM turnuvalar t JOIN sezonlar s ON s.id=t.sezon_id WHERE t.id=?');$s->execute([$id]);$t=$s->fetch();if(!$t){redirect(BASE_URL.'/admin/turnuvalar.php');}$q=$pdo->prepare('SELECT * FROM turnuva_katilimcilari WHERE turnuva_id=? ORDER BY sira');$q->execute([$id]);$katilimcilar=$q->fetchAll();if($t['tur']==='takim')$adaylar=$pdo->query("SELECT id,takim_adi ad FROM takimlar ORDER BY takim_adi")->fetchAll();else $adaylar=$pdo->query("SELECT id,CONCAT(ad,' ',soyad) ad FROM sporcular ORDER BY ad,soyad")->fetchAll();$q=$pdo->prepare('SELECT e.*,k1.sira s1,k2.sira s2 FROM turnuva_eslesmeleri e JOIN turnuva_katilimcilari k1 ON k1.id=e.katilimci1_id JOIN turnuva_katilimcilari k2 ON k2.id=e.katilimci2_id WHERE e.turnuva_id=? ORDER BY e.tur_no,e.eslesme_no');$q->execute([$id]);$eslesmeler=$q->fetchAll();}
$liste=$pdo->query('SELECT t.*,s.sezon_adi,COUNT(k.id) katilimci FROM turnuvalar t JOIN sezonlar s ON s.id=t.sezon_id LEFT JOIN turnuva_katilimcilari k ON k.turnuva_id=t.id GROUP BY t.id ORDER BY t.created_at DESC')->fetchAll();ob_start();?>
<div class="toolbar"><a href="<?= BASE_URL ?>/admin/ligler.php" class="btn">← Lig Yönetimi</a></div>
<?php if(!$t): ?><div class="card"><div class="card-head"><h2>Yeni Şampiyona / Turnuva</h2></div><form method="post" class="form"><?= csrf_field() ?><input type="hidden" name="islem" value="turnuva_olustur"><div class="grid-2"><label>Turnuva adı *<input name="turnuva_adi" required placeholder="Geleneksel Okçuluk Türkiye Şampiyonası"></label><label>Tür *<select name="tur"><option value="takim">Takım Turnuvası</option><option value="bireysel">Bireysel Turnuva</option></select></label></div><div class="grid-2"><label>Katılımcı sayısı *<select name="kontenjan"><option value="16">16 katılımcı</option><option value="32">32 katılımcı</option></select></label><label>Sezon *<select name="sezon_id"><?php foreach($sezonlar as $s): ?><option value="<?= (int)$s['id'] ?>"><?= e($s['sezon_adi']) ?></option><?php endforeach; ?></select></label></div><label>Açıklama<textarea name="aciklama"></textarea></label><button class="btn btn-primary">Turnuva Oluştur</button></form></div><?php endif; ?>
<?php if($t): ?><div class="card"><div class="card-head"><h2><?= e($t['turnuva_adi']) ?></h2><span class="badge"><?= $t['tur']==='takim'?'Takım':'Bireysel' ?> · <?= (int)$t['kontenjan'] ?> kişi/takım</span></div><?php if($t['durum']==='taslak'): ?><form method="post" class="form"><?= csrf_field() ?><input type="hidden" name="islem" value="katilimcilari_kaydet"><input type="hidden" name="turnuva_id" value="<?= $id ?>"><p class="muted">Katılımcıları A, B, C, D… sırasıyla yerleştirin. İlk tur otomatik olarak A–C ve B–D biçiminde kurulur.</p><div class="grid-2"><?php for($i=0;$i<(int)$t['kontenjan'];$i++): ?><label><?= chr(65+($i%26)).($i>=26?floor($i/26):'') ?><select name="katilimci[]" required><option value="">Seçin</option><?php foreach($adaylar as $a): ?><option value="<?= (int)$a['id'] ?>" <?= (int)($katilimcilar[$i]['hedef_id']??0)===(int)$a['id']?'selected':'' ?>><?= e($a['ad']) ?></option><?php endforeach; ?></select></label><?php endfor; ?></div><button class="btn btn-primary">Katılımcıları Kaydet</button></form><?php if(count($katilimcilar)==(int)$t['kontenjan']): ?><form method="post" class="form" onsubmit="return confirm('İlk tur eşleşmeleri oluşturulsun mu?')"><?= csrf_field() ?><input type="hidden" name="islem" value="eslesme_olustur"><input type="hidden" name="turnuva_id" value="<?= $id ?>"><button class="btn btn-primary">A–C / B–D Eşleşmelerini Oluştur</button></form><?php endif; ?><?php else: ?><div class="table-wrap"><table class="data-table"><thead><tr><th>Tur</th><th>Eşleşme</th><th>Katılımcı 1</th><th>Katılımcı 2</th></tr></thead><tbody><?php foreach($eslesmeler as $e): ?><tr><td><?= (int)$e['tur_no'] ?>. Tur</td><td><?= (int)$e['eslesme_no'] ?></td><td><?= e($e['s1']) ?></td><td><?= e($e['s2']) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div><?php endif; ?>
<div class="table-wrap"><table class="data-table"><thead><tr><th>Turnuva</th><th>Tür</th><th>Sezon</th><th>Katılımcı</th><th>Durum</th><th></th></tr></thead><tbody><?php foreach($liste as $x): ?><tr><td><?= e($x['turnuva_adi']) ?></td><td><?= $x['tur']==='takim'?'Takım':'Bireysel' ?></td><td><?= e($x['sezon_adi']) ?></td><td><?= (int)$x['katilimci'].' / '.(int)$x['kontenjan'] ?></td><td><?= e($x['durum']) ?></td><td><a class="btn btn-sm" href="?id=<?= (int)$x['id'] ?>">Yönet</a></td></tr><?php endforeach; ?></tbody></table></div>
<?php $admin_baslik='Şampiyona / Turnuva';$admin_aktif='ligler';$admin_icerik=ob_get_clean();require __DIR__.'/partials/layout.php'; ?>
