<?php
require_once __DIR__.'/config/config.php'; require_once __DIR__.'/config/database.php'; require_once __DIR__.'/includes/functions.php';

/* Varsayılan: Takım Ligi > alfabetik ilk grup > planlanan son hafta. */
$ligler=$pdo->query("SELECT id,lig_adi,tur FROM ligler WHERE aktif=1 ORDER BY tur='takim' DESC,lig_adi")->fetchAll();
$turnuvalar=$pdo->query("SELECT id,turnuva_adi,tur FROM turnuvalar ORDER BY turnuva_adi")->fetchAll();
$secenekler=[]; foreach($ligler as $x)$secenekler['lig:'.$x['id']]=['tip'=>'lig','id'=>(int)$x['id'],'ad'=>$x['lig_adi'],'tur'=>$x['tur']]; foreach($turnuvalar as $x)$secenekler['turnuva:'.$x['id']]=['tip'=>'turnuva','id'=>(int)$x['id'],'ad'=>$x['turnuva_adi'],'tur'=>$x['tur']];
$varsayilan=null; foreach($secenekler as $key=>$x)if($x['tip']==='lig'&&$x['tur']==='takim'){$varsayilan=$key;break;} if(!$varsayilan)$varsayilan=array_key_first($secenekler);
$kaynak=$_GET['kaynak']??$varsayilan; if(!isset($secenekler[$kaynak]))$kaynak=$varsayilan; $secili=$secenekler[$kaynak]??null;
$gruplar=[];$haftalar=[];$grupId=0;$hafta=0;$satirlar=[];$gorunum='lig';

if($secili&&$secili['tip']==='lig'){
    $st=$pdo->prepare('SELECT id,grup_adi FROM gruplar WHERE lig_id=? ORDER BY grup_adi');$st->execute([$secili['id']]);$gruplar=$st->fetchAll();$ids=array_map(fn($g)=>(int)$g['id'],$gruplar);
    $grupId=(int)($_GET['grup']??0);if(!in_array($grupId,$ids,true))$grupId=$ids[0]??0;
    if($secili['tur']==='takim'&&$grupId){
        $st=$pdo->prepare("SELECT DISTINCT hafta FROM maclar WHERE grup_id=? AND durum='planlandi' ORDER BY hafta");$st->execute([$grupId]);$haftalar=array_map('intval',$st->fetchAll(PDO::FETCH_COLUMN));$hafta=(int)($_GET['hafta']??0);if(!in_array($hafta,$haftalar,true))$hafta=$haftalar?end($haftalar):0;
        if($hafta){$st=$pdo->prepare("SELECT m.*,t1.takim_adi ev_adi,t2.takim_adi dep_adi,g.grup_adi,h.ad hakem_ad,h.soyad hakem_soyad FROM maclar m JOIN takimlar t1 ON t1.id=m.ev_sahibi_id JOIN takimlar t2 ON t2.id=m.deplasman_id JOIN gruplar g ON g.id=m.grup_id LEFT JOIN hakemler h ON h.id=m.hakem_id WHERE m.durum='planlandi' AND m.grup_id=? AND m.hafta=? ORDER BY m.tarih,m.saat,m.id");$st->execute([$grupId,$hafta]);$satirlar=$st->fetchAll();}
    } elseif($secili['tur']==='bireysel'&&$grupId){$gorunum='bireysel';$st=$pdo->prepare('SELECT * FROM bireysel_fikstur WHERE lig_id=? AND grup_id=? ORDER BY tarih,saat,id');$st->execute([$secili['id'],$grupId]);$satirlar=$st->fetchAll();}
} elseif($secili){
    $gorunum='turnuva';$st=$pdo->prepare("SELECT DISTINCT tur_no FROM turnuva_maclari WHERE turnuva_id=? AND durum='planlandi' ORDER BY tur_no");$st->execute([$secili['id']]);$haftalar=array_map('intval',$st->fetchAll(PDO::FETCH_COLUMN));$hafta=(int)($_GET['hafta']??0);if(!in_array($hafta,$haftalar,true))$hafta=$haftalar?end($haftalar):0;
    if($hafta){$st=$pdo->prepare("SELECT tm.*,tr.turnuva_adi,CASE WHEN tr.tur='takim' THEN t1.takim_adi ELSE CONCAT(s1.ad,' ',s1.soyad) END ev_adi,CASE WHEN tr.tur='takim' THEN t2.takim_adi ELSE CONCAT(s2.ad,' ',s2.soyad) END dep_adi FROM turnuva_maclari tm JOIN turnuvalar tr ON tr.id=tm.turnuva_id LEFT JOIN takimlar t1 ON tr.tur='takim' AND t1.id=tm.katilimci1_id LEFT JOIN takimlar t2 ON tr.tur='takim' AND t2.id=tm.katilimci2_id LEFT JOIN sporcular s1 ON tr.tur='bireysel' AND s1.id=tm.katilimci1_id LEFT JOIN sporcular s2 ON tr.tur='bireysel' AND s2.id=tm.katilimci2_id WHERE tm.turnuva_id=? AND tm.durum='planlandi' AND tm.tur_no=? ORDER BY tm.tarih,tm.saat,tm.id");$st->execute([$secili['id'],$hafta]);$satirlar=$st->fetchAll();}
}
$sayfa_baslik='Fikstür';$aktif='fikstur';require __DIR__.'/includes/header.php';
?>
<main class="main-content"><section class="page-heading"><span class="eyebrow">MÜSABAKA TAKVİMİ</span><h1>Fikstür</h1><p>Lig, turnuva, grup ve hafta seçerek planlanan karşılaşmaları görüntüleyin.</p></section>
<form method="get" class="card form"><div class="grid-3"><label>Lig / Turnuva<select name="kaynak" onchange="this.form.submit()"><?php $onceki=null;foreach($secenekler as $key=>$x):if($onceki!==$x['tip']):if($onceki!==null)echo '</optgroup>';?><optgroup label="<?= $x['tip']==='lig'?'Ligler':'Turnuvalar' ?>"><?php $onceki=$x['tip'];endif;?><option value="<?= e($key) ?>" <?= $kaynak===$key?'selected':'' ?>><?= e($x['ad']) ?><?= $x['tur']==='bireysel'?' · Bireysel':'' ?></option><?php endforeach;if($onceki!==null)echo '</optgroup>';?></select></label>
<label>Grup<?php if($secili&&$secili['tip']==='lig'):?><select name="grup" onchange="this.form.submit()"><?php foreach($gruplar as $g):?><option value="<?= (int)$g['id'] ?>" <?= $grupId===(int)$g['id']?'selected':'' ?>><?= e($g['grup_adi']) ?></option><?php endforeach;?></select><?php else:?><input value="Turnuva geneli" disabled><?php endif;?></label>
<label><?= $gorunum==='turnuva'?'Tur':'Hafta' ?><?php if($gorunum==='bireysel'):?><input value="Atış programı" disabled><?php elseif($haftalar):?><select name="hafta" onchange="this.form.submit()"><?php foreach($haftalar as $h):?><option value="<?= $h ?>" <?= $hafta===$h?'selected':'' ?>><?= $gorunum==='turnuva'?$h.'. Tur':$h.'. Hafta' ?></option><?php endforeach;?></select><?php else:?><input value="Planlanan kayıt yok" disabled><?php endif;?></label></div><noscript><div class="form-actions"><button class="btn btn-primary">Filtrele</button></div></noscript></form>
<section class="card table-card"><?php if(!$satirlar):?><p class="empty-state">Seçilen filtre için planlanmış bir kayıt bulunmuyor.</p><?php elseif($gorunum==='bireysel'):?><div class="table-wrap"><table class="data-table"><thead><tr><th>Grup</th><th>Tarih / Saat</th><th>Yer</th><th>Açıklama</th></tr></thead><tbody><?php foreach($satirlar as $x):?><tr><td><?= e($gruplar[array_search($grupId,array_column($gruplar,'id'))]['grup_adi']??'-') ?></td><td><?= tr_tarih($x['tarih']) ?> <?= tr_saat($x['saat']) ?></td><td><?= e($x['yer']) ?></td><td><?= e($x['aciklama']?:'-') ?></td></tr><?php endforeach;?></tbody></table></div><?php else:?><div class="table-wrap"><table class="data-table"><thead><tr><th><?= $gorunum==='turnuva'?'Turnuva':'Grup' ?></th><th><?= $gorunum==='turnuva'?'Tur':'Hafta' ?></th><th>Tarih / Saat</th><th>Ev Sahibi</th><th>Deplasman</th><th>Yer</th><th><?= $gorunum==='turnuva'?'Detay':'Hakem' ?></th></tr></thead><tbody><?php foreach($satirlar as $x):$url=$gorunum==='turnuva'?'turnuva-mac.php?id='.(int)$x['id']:'mac.php?id='.(int)$x['id'];?><tr><td><a href="<?= BASE_URL ?>/<?= $url ?>"><?= e($gorunum==='turnuva'?$x['turnuva_adi']:$x['grup_adi']) ?></a></td><td><?= $gorunum==='turnuva'?(int)$x['tur_no'].'. Tur':(int)$x['hafta'].'. Hafta' ?></td><td><?= tr_tarih($x['tarih']) ?> <?= tr_saat($x['saat']) ?></td><td><a href="<?= BASE_URL ?>/<?= $url ?>"><strong><?= e($x['ev_adi']?:'Belirlenecek') ?></strong></a></td><td><a href="<?= BASE_URL ?>/<?= $url ?>"><?= e($x['dep_adi']?:'Belirlenecek') ?></a></td><td><?= e($x['yer']??'-') ?></td><td><?php if($gorunum==='turnuva'):?><a href="<?= BASE_URL ?>/<?= $url ?>">Görüntüle</a><?php else:?><?= e(trim(($x['hakem_ad']??'').' '.($x['hakem_soyad']??''))?:'-') ?><?php endif;?></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section></main>
<?php require __DIR__.'/includes/sidebar.php';require __DIR__.'/includes/footer.php'; ?>
