<?php
require_once __DIR__ . '/config/config.php';
require_once __DIR__ . '/config/database.php';
require_once __DIR__ . '/includes/functions.php';
zorunlu_rol('uye', 'admin', 'yonetici', 'hakem', 'yetkili', 'sporcu');
$oturumKullanici = kullanici_bilgi();
$q = $pdo->prepare('SELECT id,kullanici_adi,email,rol,ad_soyad,son_giris,created_at FROM users WHERE id=? AND aktif=1 LIMIT 1'); $q->execute([(int)$oturumKullanici['id']]); $kullanici = $q->fetch();
if (!$kullanici) { oturum_kapat('Hesabınız artık etkin değil. Lütfen tekrar giriş yapın.'); redirect(BASE_URL . '/login.php'); }
$hata = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!csrf_check($_POST['csrf'] ?? '')) $hata = 'Güvenlik doğrulaması başarısız. Sayfayı yenileyip tekrar deneyin.';
    elseif (($_POST['islem'] ?? '') === 'profil') {
        $adSoyad = trim($_POST['ad_soyad'] ?? ''); $email = trim($_POST['email'] ?? '');
        if (mb_strlen($adSoyad) < 2 || mb_strlen($adSoyad) > 120) $hata = 'Ad soyad 2-120 karakter arasında olmalıdır.';
        elseif (!filter_var($email, FILTER_VALIDATE_EMAIL) || mb_strlen($email) > 120) $hata = 'Geçerli bir e-posta adresi girin.';
        else { $kontrol=$pdo->prepare('SELECT id FROM users WHERE email=? AND id<>? LIMIT 1'); $kontrol->execute([$email,(int)$kullanici['id']]); if($kontrol->fetch()) $hata='Bu e-posta başka bir hesap tarafından kullanılıyor.'; else { $pdo->prepare('UPDATE users SET ad_soyad=?, email=? WHERE id=?')->execute([$adSoyad,$email,(int)$kullanici['id']]); $_SESSION['kullanici']['ad_soyad']=$adSoyad; $_SESSION['kullanici']['email']=$email; flash_set('basari','Profil bilgileriniz güncellendi.'); redirect(hesap_sayfasi_url()); } }
    } elseif (($_POST['islem'] ?? '') === 'sifre') {
        $mevcut=$_POST['mevcut_sifre']??''; $yeni=$_POST['yeni_sifre']??''; $tekrar=$_POST['yeni_sifre_tekrar']??''; $q=$pdo->prepare('SELECT sifre FROM users WHERE id=? LIMIT 1'); $q->execute([(int)$kullanici['id']]); $hash=(string)$q->fetchColumn();
        if (!sifre_dogrula($mevcut,$hash)) $hata='Mevcut şifreniz doğru değil.';
        elseif (strlen($yeni)<8 || strlen($yeni)>72) $hata='Yeni şifre 8-72 karakter arasında olmalıdır.';
        elseif ($yeni!==$tekrar) $hata='Yeni şifreler eşleşmiyor.';
        else { $pdo->prepare('UPDATE users SET sifre=? WHERE id=?')->execute([sifre_hash($yeni),(int)$kullanici['id']]); session_regenerate_id(true); unset($_SESSION['csrf_token']); flash_set('basari','Şifreniz güncellendi.'); redirect(hesap_sayfasi_url()); }
    }
}
$q=$pdo->prepare('SELECT tur,COUNT(*) adet FROM favoriler WHERE user_id=? GROUP BY tur'); $q->execute([(int)$kullanici['id']]); $favoriSayilari=['takim'=>0,'sporcu'=>0]; foreach($q->fetchAll() as $satir) $favoriSayilari[$satir['tur']]=(int)$satir['adet'];
$rolAdlari=['uye'=>'Üye','admin'=>'Yönetici','yonetici'=>'Sınırlı Yönetici','hakem'=>'Hakem','yetkili'=>'Takım Yetkilisi','sporcu'=>'Sporcu']; $sayfa_baslik='Hesabım'; require_once __DIR__ . '/includes/header.php';
?>
<main class="main-content"><section class="page-heading"><span>Üye merkezi</span><h1>Hesabım</h1><p>Profilinizi yönetin, takip ettiklerinize ulaşın ve yetkiniz varsa yönetim alanına buradan geçin.</p></section><?php if($hata): ?><div class="flash flash-hata"><?= e($hata) ?></div><?php endif; ?><section class="hesap-ozet card"><div><span class="hesap-avatar"><?= e(mb_strtoupper(mb_substr($kullanici['ad_soyad']?:$kullanici['kullanici_adi'],0,1))) ?></span></div><div class="hesap-kimlik"><h2><?= e($kullanici['ad_soyad']?:$kullanici['kullanici_adi']) ?></h2><p>@<?= e($kullanici['kullanici_adi']) ?> · <span class="badge"><?= e($rolAdlari[$kullanici['rol']]??$kullanici['rol']) ?></span></p><small>Üyelik: <?= tr_tarih($kullanici['created_at']) ?></small></div><div class="hesap-eylemler"><a class="btn btn-ghost" href="<?= BASE_URL ?>/favorilerim.php">★ Favorilerim</a><?php if(yonetim_paneli_erisimi_var($kullanici['rol'])): ?><a class="btn btn-primary" href="<?= BASE_URL ?>/admin/">Yönetim Paneli</a><?php endif; ?><a class="btn btn-outline" href="<?= BASE_URL ?>/logout.php">Çıkış yap</a></div></section><section class="hesap-istatistik"><a href="<?= BASE_URL ?>/favorilerim.php#takimlar"><strong><?= $favoriSayilari['takim'] ?></strong><span>Takip edilen takım</span></a><a href="<?= BASE_URL ?>/favorilerim.php#sporcular"><strong><?= $favoriSayilari['sporcu'] ?></strong><span>Takip edilen sporcu</span></a><div><strong><?= $kullanici['son_giris']?tr_tarih_saat($kullanici['son_giris']):'İlk giriş' ?></strong><span>Son giriş</span></div></section><div class="hesap-grid"><section class="card"><div class="card-head"><h2>Profil bilgileri</h2></div><form method="post" class="form"><?= csrf_field() ?><input type="hidden" name="islem" value="profil"><label>Ad Soyad<input name="ad_soyad" required maxlength="120" value="<?= e($kullanici['ad_soyad']) ?>" autocomplete="name"></label><label>E-posta<input type="email" name="email" required maxlength="120" value="<?= e($kullanici['email']) ?>" autocomplete="email"></label><div class="form-actions"><button class="btn btn-primary">Bilgileri Kaydet</button></div></form></section><section class="card"><div class="card-head"><h2>Şifre değiştir</h2></div><form method="post" class="form"><?= csrf_field() ?><input type="hidden" name="islem" value="sifre"><label>Mevcut şifre<input type="password" name="mevcut_sifre" required autocomplete="current-password"></label><label>Yeni şifre<input type="password" name="yeni_sifre" required minlength="8" maxlength="72" autocomplete="new-password"></label><label>Yeni şifre tekrar<input type="password" name="yeni_sifre_tekrar" required minlength="8" maxlength="72" autocomplete="new-password"></label><p class="muted">En az 8 karakter uzunluğunda, size özgü bir şifre kullanın.</p><div class="form-actions"><button class="btn btn-outline">Şifreyi Güncelle</button></div></form></section></div></main>
<?php require_once __DIR__ . '/includes/sidebar.php'; require_once __DIR__ . '/includes/footer.php'; ?>
