<?php
require_once __DIR__.'/config/config.php';require_once __DIR__.'/config/database.php';require_once __DIR__.'/includes/functions.php';
$tur=$_GET['tur']??'takim_ligi';$sec=['takim_ligi'=>'Takım Ligleri','bireysel_lig'=>'Bireysel Bölge Ligleri','takim_turnuvasi'=>'Takım Turnuvaları','bireysel_turnuvasi'=>'Bireysel Turnuvalar'];if(!isset($sec[$tur]))$tur='takim_ligi';
$ligTuru=$tur==='bireysel_lig'?'bireysel':'takim';$ligler=[];$gruplar=[];$kategoriler=[];$ligId=0;$grupId=0;$kategori='';
if(in_array($tur,['takim_ligi','bireysel_lig'],true)){
    $st=$pdo->prepare('SELECT id,lig_adi FROM ligler WHERE aktif=1 AND tur=? ORDER BY lig_adi');$st->execute([$ligTuru]);$ligler=$st->fetchAll();$ligId=(int)($_GET['lig_id']??0);$ligIds=array_map(fn($l)=>(int)$l['id'],$ligler);if($ligId&&!in_array($ligId,$ligIds,true))$ligId=0;
    if($ligId){$st=$pdo->prepare('SELECT id,grup_adi,bolge_adi,kategori_adi FROM gruplar WHERE lig_id=? ORDER BY bolge_adi,grup_adi');$st->execute([$ligId]);$gruplar=$st->fetchAll();}else{$st=$pdo->prepare('SELECT g.id,g.grup_adi,g.bolge_adi,g.kategori_adi FROM gruplar g JOIN ligler l ON l.id=g.lig_id WHERE l.tur=? ORDER BY g.bolge_adi,g.grup_adi');$st->execute([$ligTuru]);$gruplar=$st->fetchAll();}
    $grupId=(int)($_GET['grup_id']??0);$grupIds=array_map(fn($g)=>(int)$g['id'],$gruplar);if($grupId&&!in_array($grupId,$grupIds,true))$grupId=0;
    if($tur==='bireysel_lig'){$kategoriler=array_values(array_unique(array_filter(array_column($gruplar,'kategori_adi'))));sort($kategoriler,SORT_NATURAL|SORT_FLAG_CASE);$kategori=trim($_GET['kategori']??'');if($kategori&&!in_array($kategori,$kategoriler,true))$kategori='';}
}
$sayfa_baslik='Karşılaşma Sonuçları';$aktif='sonuclar';require __DIR__.'/includes/header.php';
?>
<main class="main-content"><section class="page-heading"><span>SONUÇ MERKEZİ</span><h1>Karşılaşma Sonuçları</h1><p>Sonuç türünü seçerek tamamlanan karşılaşmaları takip edin.</p></section>
<nav class="sonuc-sekmeleri"><?php foreach($sec as $k=>$v): ?><a href="?tur=<?= $k ?>" class="<?= $tur===$k?'active':'' ?>"><?= $v ?></a><?php endforeach; ?></nav>
<?php if(in_array($tur,['takim_ligi','bireysel_lig'],true)): ?><form method="get" class="card form"><input type="hidden" name="tur" value="<?= e($tur) ?>"><div class="grid-3"><label>Lig<select name="lig_id" onchange="this.form.submit()"><option value="0">Tüm Ligler</option><?php foreach($ligler as $lig): ?><option value="<?= (int)$lig['id'] ?>" <?= $ligId===(int)$lig['id']?'selected':'' ?>><?= e($lig['lig_adi']) ?></option><?php endforeach; ?></select></label><label>Grup<select name="grup_id" onchange="this.form.submit()"><option value="0">Tüm Gruplar</option><?php foreach($gruplar as $grup): ?><option value="<?= (int)$grup['id'] ?>" <?= $grupId===(int)$grup['id']?'selected':'' ?>><?= e($tur==='bireysel_lig'?($grup['bolge_adi']?:$grup['grup_adi']):$grup['grup_adi']) ?></option><?php endforeach; ?></select></label><?php if($tur==='bireysel_lig'): ?><label>Kategori<select name="kategori" onchange="this.form.submit()"><option value="">Tüm Kategoriler</option><?php foreach($kategoriler as $k): ?><option value="<?= e($k) ?>" <?= $kategori===$k?'selected':'' ?>><?= e($k) ?></option><?php endforeach; ?></select></label><?php else: ?><label>Kategori<input value="Takım liglerinde uygulanmaz" disabled></label><?php endif; ?></div><noscript><div class="form-actions"><button class="btn btn-primary">Filtrele</button></div></noscript></form><?php endif; ?>
<section class="card">
<?php if($tur==='takim_ligi'):
    $kosul="l.tur='takim' AND m.durum='oynandi'";$param=[];if($ligId){$kosul.=' AND l.id=?';$param[]=$ligId;}if($grupId){$kosul.=' AND g.id=?';$param[]=$grupId;}$st=$pdo->prepare("SELECT COALESCE(MAX(m.hafta),0) FROM maclar m JOIN gruplar g ON g.id=m.grup_id JOIN ligler l ON l.id=g.lig_id WHERE $kosul");$st->execute($param);$sonHafta=(int)$st->fetchColumn();$q=$pdo->prepare("SELECT m.*,a.takim_adi ev,b.takim_adi dep,g.grup_adi,l.lig_adi FROM maclar m JOIN takimlar a ON a.id=m.ev_sahibi_id JOIN takimlar b ON b.id=m.deplasman_id JOIN gruplar g ON g.id=m.grup_id JOIN ligler l ON l.id=g.lig_id WHERE $kosul AND m.hafta=? ORDER BY g.grup_adi,m.tarih,m.id");$q->execute(array_merge($param,[$sonHafta]));$maclar=$q->fetchAll(); ?>
    <div class="card-head"><h2><?= $sonHafta ? $sonHafta.'. Hafta Sonuçları' : 'Son Hafta Sonuçları' ?></h2><span class="badge"><?= count($maclar) ?> karşılaşma</span></div><?php if(!$maclar): ?><p class="muted">Bu filtre için tamamlanan Takım Ligi karşılaşması bulunmuyor.</p><?php else: ?><div class="match-list"><?php foreach($maclar as $x): ?><article><small><?= e($x['lig_adi'].' · '.$x['grup_adi']) ?></small><strong><a href="<?= BASE_URL ?>/mac.php?id=<?= (int)$x['id'] ?>"><?= e($x['ev']) ?> <span><?= (int)$x['ev_sahibi_set'] ?> - <?= (int)$x['deplasman_set'] ?></span> <?= e($x['dep']) ?></a></strong><a class="btn btn-sm" href="<?= BASE_URL ?>/mac.php?id=<?= (int)$x['id'] ?>">Detay</a></article><?php endforeach; ?></div><?php endif; ?>
<?php elseif($tur==='bireysel_lig'):
    $kosul="l.tur='bireysel'";$param=[];if($ligId){$kosul.=' AND l.id=?';$param[]=$ligId;}if($grupId){$kosul.=' AND g.id=?';$param[]=$grupId;}if($kategori!==''){$kosul.=' AND g.kategori_adi=?';$param[]=$kategori;}$q=$pdo->prepare("SELECT k.sporcu_id,s.ad,s.soyad,k.toplam_puan,l.lig_adi,g.grup_adi,g.bolge_adi,g.kategori_adi FROM bireysel_lig_kayitlari k JOIN sporcular s ON s.id=k.sporcu_id JOIN ligler l ON l.id=k.lig_id JOIN gruplar g ON g.id=k.grup_id WHERE $kosul ORDER BY k.toplam_puan DESC,s.ad,s.soyad");$q->execute($param);$kayitlar=$q->fetchAll(); ?>
    <div class="card-head"><h2>Bireysel Bölge Ligleri</h2><span class="badge"><?= count($kayitlar) ?> sporcu</span></div><?php if(!$kayitlar): ?><p class="muted">Bu filtre için sporcu sonucu bulunmuyor.</p><?php else: ?><div class="table-wrap"><table class="data-table"><thead><tr><th>Lig / Grup</th><th>Kategori</th><th>Sporcu</th><th>Puan</th></tr></thead><tbody><?php foreach($kayitlar as $x): ?><tr><td><?= e($x['lig_adi'].' · '.($x['bolge_adi']?:$x['grup_adi'])) ?></td><td><?= e($x['kategori_adi']) ?></td><td><a href="<?= BASE_URL ?>/sporcu.php?id=<?= (int)$x['sporcu_id'] ?>"><?= e($x['ad'].' '.$x['soyad']) ?></a></td><td><?= (int)$x['toplam_puan'] ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?>
<?php else:
    $turnuvaTuru=$tur==='takim_turnuvasi'?'takim':'bireysel';$q=$pdo->prepare("SELECT tm.*,t.turnuva_adi,CASE WHEN t.tur='takim' THEN ev_t.takim_adi ELSE CONCAT(ev_s.ad,' ',ev_s.soyad) END ev,CASE WHEN t.tur='takim' THEN dep_t.takim_adi ELSE CONCAT(dep_s.ad,' ',dep_s.soyad) END dep FROM turnuva_maclari tm JOIN turnuvalar t ON t.id=tm.turnuva_id LEFT JOIN takimlar ev_t ON t.tur='takim' AND ev_t.id=tm.katilimci1_id LEFT JOIN takimlar dep_t ON t.tur='takim' AND dep_t.id=tm.katilimci2_id LEFT JOIN sporcular ev_s ON t.tur='bireysel' AND ev_s.id=tm.katilimci1_id LEFT JOIN sporcular dep_s ON t.tur='bireysel' AND dep_s.id=tm.katilimci2_id WHERE t.tur=? AND tm.durum='oynandi' ORDER BY t.turnuva_adi,tm.tur_no,tm.id");$q->execute([$turnuvaTuru]);$turnuvaMaclari=$q->fetchAll(); ?>
    <div class="card-head"><h2><?= $sec[$tur] ?></h2><span class="badge"><?= count($turnuvaMaclari) ?> karşılaşma</span></div><?php if(!$turnuvaMaclari): ?><p class="muted">Henüz tamamlanan <?= $sec[$tur] ?> karşılaşması bulunmuyor.</p><?php else: ?><div class="match-list"><?php foreach($turnuvaMaclari as $x): ?><article><small><?= e($x['turnuva_adi'].' · '.$x['tur_no'].'. Tur') ?></small><strong><a href="<?= BASE_URL ?>/turnuva-mac.php?id=<?= (int)$x['id'] ?>"><?= e($x['ev']?:'—') ?> <span><?= (int)$x['puan1'] ?> - <?= (int)$x['puan2'] ?></span> <?= e($x['dep']?:'—') ?></a></strong><a class="btn btn-sm" href="<?= BASE_URL ?>/turnuva-mac.php?id=<?= (int)$x['id'] ?>">Detay</a></article><?php endforeach; ?></div><?php endif; ?>
<?php endif; ?>
</section></main>
<?php require __DIR__.'/includes/sidebar.php';require __DIR__.'/includes/footer.php'; ?>
