<?php
require_once __DIR__.'/config/config.php'; require_once __DIR__.'/config/database.php'; require_once __DIR__.'/includes/functions.php';
$id=(int)($_GET['id']??0);$q=$pdo->prepare('SELECT t.*,s.sezon_adi FROM turnuvalar t JOIN sezonlar s ON s.id=t.sezon_id WHERE t.id=?');$q->execute([$id]);$t=$q->fetch();if(!$t)redirect(BASE_URL.'/turnuvalar.php');
$q=$pdo->prepare("SELECT tm.*,e.eslesme_no,CASE WHEN t.tur='takim' THEN a.takim_adi ELSE CONCAT(sa.ad,' ',sa.soyad) END ev,CASE WHEN t.tur='takim' THEN b.takim_adi ELSE CONCAT(sb.ad,' ',sb.soyad) END dep FROM turnuva_maclari tm JOIN turnuvalar t ON t.id=tm.turnuva_id JOIN turnuva_eslesmeleri e ON e.id=tm.eslesme_id LEFT JOIN takimlar a ON a.id=tm.katilimci1_id LEFT JOIN takimlar b ON b.id=tm.katilimci2_id LEFT JOIN sporcular sa ON sa.id=tm.katilimci1_id LEFT JOIN sporcular sb ON sb.id=tm.katilimci2_id WHERE tm.turnuva_id=? ORDER BY tm.tur_no,e.eslesme_no");$q->execute([$id]);$maclar=$q->fetchAll();$turlar=[];foreach($maclar as $m)$turlar[$m['tur_no']][]=$m;$turSayisi=(int)round(log((int)$t['kontenjan'],2));
function tur_adi($tur,$toplam){if($tur===$toplam)return 'Final';if($tur===$toplam-1)return 'Yarı Final';if($tur===$toplam-2)return 'Çeyrek Final';return $tur.'. Tur';}
$sayfa_baslik=$t['turnuva_adi'];$aktif='turnuvalar';require __DIR__.'/includes/header.php';
?>
<main class="main-content"><section class="page-heading"><span>TURNUVA</span><h1><?= e($t['turnuva_adi']) ?></h1><p><?= e($t['sezon_adi']) ?> · <?= $t['tur']==='takim'?'Takım':'Bireysel' ?> Turnuvası</p></section>
<section class="card turnuva-ag-kart"><div class="card-head"><h2>Turnuva Ağacı</h2><span class="badge">Eşleşmeye veya skora tıklayarak detayları görüntüleyin</span></div><div class="turnuva-ag tur-sayisi-<?= $turSayisi ?>"><?php for($tur=1;$tur<=$turSayisi;$tur++): ?><div class="ag-turu ag-tur-<?= $tur ?>"><h3><?= tur_adi($tur,$turSayisi) ?></h3><div class="ag-maclar"><?php foreach($turlar[$tur]??[] as $m): ?><a class="ag-mac <?= $m['durum']==='oynandi'?'tamamlandi':'' ?>" href="<?= BASE_URL ?>/turnuva-mac.php?id=<?= (int)$m['id'] ?>"><span><?= e($m['ev'] ?: 'Kazanan bekleniyor') ?></span><b><?= (int)$m['puan1'] ?> <i>—</i> <?= (int)$m['puan2'] ?></b><span><?= e($m['dep'] ?: 'Kazanan bekleniyor') ?></span></a><?php endforeach; ?></div></div><?php endfor; ?></div></section>
<section class="card"><div class="card-head"><h2>Karşılaşmalar</h2><span class="badge">Tıklayarak takip edin</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Tur</th><th>Ev</th><th>Skor</th><th>Misafir</th><th>Durum</th></tr></thead><tbody><?php foreach($maclar as $m): ?><tr><td><?= e(tur_adi((int)$m['tur_no'],$turSayisi)) ?></td><td><?= e($m['ev'] ?: 'Bekleniyor') ?></td><td><a href="<?= BASE_URL ?>/turnuva-mac.php?id=<?= (int)$m['id'] ?>"><?= (int)$m['puan1'] ?> - <?= (int)$m['puan2'] ?></a></td><td><?= e($m['dep'] ?: 'Bekleniyor') ?></td><td><?= $m['durum']==='oynandi'?'Tamamlandı':'Planlandı' ?></td></tr><?php endforeach; ?></tbody></table></div></section></main>
<?php require __DIR__.'/includes/sidebar.php';require __DIR__.'/includes/footer.php'; ?>
