<?php
require_once __DIR__.'/../config/config.php';require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/functions.php';zorunlu_rol('admin','yonetici');
$ligId=(int)($_GET['lig_id']??$_POST['lig_id']??0);$q=$pdo->prepare('SELECT * FROM ligler WHERE id=?');$q->execute([$ligId]);$lig=$q->fetch();if(!$lig){flash_set('hata','Lig bulunamadı.');redirect(BASE_URL.'/admin/gruplar-ve-fikstur.php');}
if($lig['tur']==='bireysel')redirect(BASE_URL.'/admin/bireysel-fikstur.php?lig_id='.$ligId);
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!csrf_check($_POST['csrf']??'')){flash_set('hata','Güvenlik doğrulaması başarısız.');redirect(BASE_URL.'/admin/lig-fikstur.php?lig_id='.$ligId);}
 $grupId=(int)($_POST['grup_id']??0);$q=$pdo->prepare('SELECT id FROM gruplar WHERE id=? AND lig_id=?');$q->execute([$grupId,$ligId]);if(!$q->fetch()){flash_set('hata','Grup bulunamadı.');redirect(BASE_URL.'/admin/lig-fikstur.php?lig_id='.$ligId);}
 if(($_POST['islem']??'')==='sil'){$pdo->prepare('DELETE FROM maclar WHERE grup_id=?')->execute([$grupId]);flash_set('basari','Grubun oluşturulmuş fikstürü tamamen silindi.');}
 if(($_POST['islem']??'')==='olustur'){
  $q=$pdo->prepare('SELECT id FROM takimlar WHERE grup_id=? ORDER BY id');$q->execute([$grupId]);$takimlar=array_column($q->fetchAll(),'id');if(count($takimlar)!==6){flash_set('hata','Fikstür oluşturmak için grupta tam 6 takım bulunmalıdır.');redirect(BASE_URL.'/admin/lig-fikstur.php?lig_id='.$ligId);}
  $mevcut=$pdo->prepare('SELECT COUNT(*) FROM maclar WHERE grup_id=?');$mevcut->execute([$grupId]);if((int)$mevcut->fetchColumn()>0){flash_set('hata','Bu grup için zaten fikstür var. Yeniden oluşturmak için önce Sil düğmesini kullanın.');redirect(BASE_URL.'/admin/lig-fikstur.php?lig_id='.$ligId);}
  $dizi=$takimlar;$ilkTur=[];for($hafta=1;$hafta<=5;$hafta++){for($i=0;$i<3;$i++)$ilkTur[]=[$hafta,$dizi[$i],$dizi[5-$i]];$sabit=$dizi[0];$kalan=array_slice($dizi,1);array_unshift($kalan,array_pop($kalan));$dizi=array_merge([$sabit],$kalan);}
  $ekle=$pdo->prepare("INSERT INTO maclar(grup_id,ev_sahibi_id,deplasman_id,hafta,durum) VALUES(?,?,?,?, 'planlandi')");foreach($ilkTur as [$hafta,$ev,$dep])$ekle->execute([$grupId,$ev,$dep,$hafta]);foreach($ilkTur as [$hafta,$ev,$dep])$ekle->execute([$grupId,$dep,$ev,$hafta+5]);flash_set('basari','Çift devreli fikstür oluşturuldu: 10 hafta, 30 karşılaşma.');
 }
 redirect(BASE_URL.'/admin/lig-fikstur.php?lig_id='.$ligId);
}
$q=$pdo->prepare('SELECT g.*,COUNT(m.id) mac_sayisi FROM gruplar g LEFT JOIN maclar m ON m.grup_id=g.id WHERE g.lig_id=? GROUP BY g.id ORDER BY g.grup_adi');$q->execute([$ligId]);$gruplar=$q->fetchAll();ob_start();?>
<div class="toolbar"><a class="btn btn-outline" href="<?= BASE_URL ?>/admin/gruplar-ve-fikstur.php">← Gruplar ve Fikstür</a></div>
<section class="card"><div class="card-head"><h2><?= e($lig['lig_adi']) ?> Fikstürü</h2><span class="badge">Takım Ligi</span></div><p class="muted">Her grup için 6 takımın çift devreli, 10 haftalık fikstürü oluşturulur.</p><div class="table-wrap"><table class="data-table"><thead><tr><th>Grup</th><th>Karşılaşma</th><th>İşlem</th></tr></thead><tbody><?php foreach($gruplar as $g):?><tr><td><strong><?= e($g['grup_adi']) ?></strong></td><td><?= (int)$g['mac_sayisi'] ?> / 30</td><td><form method="post" class="inline-form"><?= csrf_field() ?><input type="hidden" name="lig_id" value="<?= $ligId ?>"><input type="hidden" name="grup_id" value="<?= (int)$g['id'] ?>"><input type="hidden" name="islem" value="olustur"><button class="btn btn-sm btn-primary">Oluştur</button></form><form method="post" class="inline-form" onsubmit="return confirm('Bu grubun tüm karşılaşmaları silinsin mi?')"><?= csrf_field() ?><input type="hidden" name="lig_id" value="<?= $ligId ?>"><input type="hidden" name="grup_id" value="<?= (int)$g['id'] ?>"><input type="hidden" name="islem" value="sil"><button class="btn btn-sm btn-danger">Sil</button></form></td></tr><?php endforeach;?></tbody></table></div></section>
<?php $admin_baslik='Lig Fikstürü';$admin_aktif='ligler';$admin_geri_url=BASE_URL.'/admin/gruplar-ve-fikstur.php';$admin_geri_ad='Gruplar ve Fikstür';$admin_icerik=ob_get_clean();require __DIR__.'/partials/layout.php';?>
