<?php
require_once __DIR__.'/../config/config.php';require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/functions.php';zorunlu_rol('admin','yonetici');
$islem=$_GET['islem']??'liste';$id=(int)($_GET['id']??0);
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!csrf_check($_POST['csrf']??'')){flash_set('hata','Güvenlik doğrulaması başarısız.');redirect(BASE_URL.'/admin/uyeler.php');}
 $ad=trim($_POST['ad_soyad']??'');$email=trim($_POST['email']??'');$kadi=trim($_POST['kullanici_adi']??'');$sifre=$_POST['sifre']??'';$aktif=isset($_POST['aktif'])?1:0;
 if($ad===''||$email===''||$kadi===''){flash_set('hata','Ad soyad, e-posta ve kullanıcı adı zorunludur.');redirect(BASE_URL.'/admin/uyeler.php?islem='.($_POST['islem']??'ekle').'&id='.(int)($_POST['id']??0));}
 $kontrol=$pdo->prepare('SELECT id FROM users WHERE (kullanici_adi=? OR email=?) AND id<>?');$kontrol->execute([$kadi,$email,(int)($_POST['id']??0)]);if($kontrol->fetch()){flash_set('hata','Kullanıcı adı veya e-posta zaten kullanımda.');redirect(BASE_URL.'/admin/uyeler.php?islem='.($_POST['islem']??'ekle'));}
 if(($_POST['islem']??'')==='ekle'){if(strlen($sifre)<8){flash_set('hata','Şifre en az 8 karakter olmalıdır.');redirect(BASE_URL.'/admin/uyeler.php?islem=ekle');}$pdo->prepare("INSERT INTO users(kullanici_adi,email,sifre,rol,ad_soyad,aktif) VALUES(?,?,?,'uye',?,?)")->execute([$kadi,$email,sifre_hash($sifre),$ad,$aktif]);flash_set('basari','Üye eklendi.');}
 else {$uid=(int)$_POST['id'];$pdo->prepare("UPDATE users SET kullanici_adi=?,email=?,ad_soyad=?,aktif=? WHERE id=? AND rol='uye'")->execute([$kadi,$email,$ad,$aktif,$uid]);if($sifre!==''){$pdo->prepare("UPDATE users SET sifre=? WHERE id=? AND rol='uye'")->execute([sifre_hash($sifre),$uid]);}flash_set('basari','Üye güncellendi.');}
 redirect(BASE_URL.'/admin/uyeler.php');
}
$duzenlenen=null;if($islem==='duzenle'&&$id){$q=$pdo->prepare("SELECT * FROM users WHERE id=? AND rol='uye'");$q->execute([$id]);$duzenlenen=$q->fetch();if(!$duzenlenen)redirect(BASE_URL.'/admin/uyeler.php');}
$liste=$pdo->query("SELECT * FROM users WHERE rol='uye' ORDER BY created_at DESC")->fetchAll();ob_start();?>
<?php if($islem==='ekle'||$islem==='duzenle'): ?><form method="post" class="form"><?= csrf_field() ?><input type="hidden" name="islem" value="<?= e($islem) ?>"><?php if($duzenlenen):?><input type="hidden" name="id" value="<?= (int)$duzenlenen['id'] ?>"><?php endif;?><div class="grid-2"><label>Ad Soyad *<input name="ad_soyad" required value="<?= e($duzenlenen['ad_soyad']??'') ?>"></label><label>E-posta *<input type="email" name="email" required value="<?= e($duzenlenen['email']??'') ?>"></label></div><div class="grid-2"><label>Kullanıcı Adı *<input name="kullanici_adi" required value="<?= e($duzenlenen['kullanici_adi']??'') ?>"></label><label>Şifre <?= $duzenlenen?'(boşsa değişmez)':'*' ?><input type="password" name="sifre" <?= $duzenlenen?'':'required' ?>></label></div><label class="check-line"><input type="checkbox" name="aktif" value="1" <?= (!$duzenlenen||$duzenlenen['aktif'])?'checked':'' ?>> Giriş yapabilir</label><div class="form-actions"><button class="btn btn-primary"><?= $duzenlenen?'Güncelle':'Üye Ekle' ?></button><a class="btn btn-outline" href="<?= BASE_URL ?>/admin/uyeler.php">İptal</a></div></form><?php else:?><div class="toolbar"><a class="btn btn-primary" href="?islem=ekle">+ Yeni Üye</a></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Ad Soyad</th><th>Kullanıcı Adı</th><th>E-posta</th><th>Durum</th><th></th></tr></thead><tbody><?php foreach($liste as $uye):?><tr><td><?= e($uye['ad_soyad']) ?></td><td><?= e($uye['kullanici_adi']) ?></td><td><?= e($uye['email']) ?></td><td><?= $uye['aktif']?'Aktif':'Pasif' ?></td><td><a class="btn btn-sm" href="?islem=duzenle&id=<?= (int)$uye['id'] ?>">Düzenle</a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?><?php $admin_baslik='Üyeler';$admin_aktif='uyeler';$admin_icerik=ob_get_clean();require __DIR__.'/partials/layout.php';
