<?php
require_once __DIR__.'/../config/config.php';require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/functions.php';zorunlu_rol('admin','yonetici','hakem');
$fiksturId=(int)($_GET['fikstur_id']??$_POST['fikstur_id']??0);
$q=$pdo->prepare('SELECT f.*,l.lig_adi,g.grup_adi,g.bolge_adi,g.kategori_adi FROM bireysel_fikstur f JOIN ligler l ON l.id=f.lig_id JOIN gruplar g ON g.id=f.grup_id WHERE f.id=? AND l.tur=\'bireysel\'');$q->execute([$fiksturId]);$fikstur=$q->fetch();
if(!$fikstur){flash_set('hata','Bireysel atış planı bulunamadı.');redirect(BASE_URL.'/admin/mac-skor.php?kaynak=lig&lig_tur=bireysel');}
$sporcuS=$pdo->prepare('SELECT s.id,s.ad,s.soyad FROM bireysel_lig_kayitlari k JOIN sporcular s ON s.id=k.sporcu_id WHERE k.lig_id=? AND k.grup_id=? ORDER BY s.ad,s.soyad');$sporcuS->execute([$fikstur['lig_id'],$fikstur['grup_id']]);$sporcular=$sporcuS->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!csrf_check($_POST['csrf']??'')){flash_set('hata','Güvenlik doğrulaması başarısız.');redirect(BASE_URL.'/admin/bireysel-skor.php?fikstur_id='.$fiksturId);}
    try{$pdo->beginTransaction();$pdo->prepare('DELETE FROM bireysel_fikstur_atislari WHERE fikstur_id=?')->execute([$fiksturId]);$ekle=$pdo->prepare('INSERT INTO bireysel_fikstur_atislari(fikstur_id,sporcu_id,puan) VALUES(?,?,?)');foreach($sporcular as $sporcu)$ekle->execute([$fiksturId,$sporcu['id'],max(0,min(21,(int)($_POST['puan'][$sporcu['id']]??0)))]);
        $toplam=$pdo->prepare('SELECT a.sporcu_id,COALESCE(SUM(a.puan),0) toplam,COUNT(a.id) atis FROM bireysel_fikstur_atislari a JOIN bireysel_fikstur f ON f.id=a.fikstur_id WHERE f.lig_id=? AND f.grup_id=? GROUP BY a.sporcu_id');$toplam->execute([$fikstur['lig_id'],$fikstur['grup_id']]);$guncelle=$pdo->prepare('UPDATE bireysel_lig_kayitlari SET toplam_puan=?,atis_sayisi=? WHERE lig_id=? AND grup_id=? AND sporcu_id=?');foreach($toplam->fetchAll() as $satir)$guncelle->execute([$satir['toplam'],$satir['atis'],$fikstur['lig_id'],$fikstur['grup_id'],$satir['sporcu_id']]);$pdo->commit();flash_set('basari','Haftalık bireysel atış puanları kaydedildi.');}
    catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash_set('hata',$e->getMessage());}
    redirect(BASE_URL.'/admin/bireysel-skor.php?fikstur_id='.$fiksturId);
}
$mevcutS=$pdo->prepare('SELECT sporcu_id,puan FROM bireysel_fikstur_atislari WHERE fikstur_id=?');$mevcutS->execute([$fiksturId]);$mevcut=array_column($mevcutS->fetchAll(),'puan','sporcu_id');
$hafta=!empty($fikstur['hafta_no'])?(int)$fikstur['hafta_no'].'. Hafta':e($fikstur['aciklama']?:'Atış');ob_start();?>
<div class="toolbar"><a class="btn btn-outline" href="<?= BASE_URL ?>/admin/mac-skor.php?kaynak=lig&lig_tur=bireysel&grup_id=<?= (int)$fikstur['grup_id'] ?>">← Skor Girişi</a></div>
<form method="post" class="form"><section class="card"><div class="card-head"><h2><?= e($fikstur['lig_adi']) ?> · <?= e($fikstur['bolge_adi']?:$fikstur['grup_adi']) ?></h2><span class="badge"><?= $hafta ?></span></div><p class="muted"><?= e($fikstur['kategori_adi']) ?> · <?= tr_tarih($fikstur['tarih']) ?> · <?= e($fikstur['yer']) ?>. Her sporcu 7 okun toplamı olarak en fazla 21 puan alabilir.</p><?= csrf_field() ?><input type="hidden" name="fikstur_id" value="<?= $fiksturId ?>"><div class="table-wrap"><table class="data-table"><thead><tr><th>Sporcu</th><th>Atış Puanı</th></tr></thead><tbody><?php foreach($sporcular as $sporcu): ?><tr><td><?= e($sporcu['ad'].' '.$sporcu['soyad']) ?></td><td><input type="number" name="puan[<?= (int)$sporcu['id'] ?>]" min="0" max="21" required value="<?= (int)($mevcut[$sporcu['id']]??0) ?>"></td></tr><?php endforeach; ?><?php if(!$sporcular): ?><tr><td colspan="2" class="muted">Bu grup-kategoriye kayıtlı sporcu bulunmuyor.</td></tr><?php endif; ?></tbody></table></div><div class="form-actions"><button class="btn btn-primary" <?= !$sporcular?'disabled':'' ?>>Puanları Kaydet</button></div></section></form>
<?php $admin_baslik='Bireysel Lig Skor Girişi';$admin_aktif='skor';$admin_geri_url=BASE_URL.'/admin/mac-skor.php?kaynak=lig&lig_tur=bireysel';$admin_geri_ad='Skor Girişi';$admin_icerik=ob_get_clean();require __DIR__.'/partials/layout.php'; ?>
