<?php
require_once __DIR__.'/../config/config.php';require_once __DIR__.'/../config/database.php';require_once __DIR__.'/../includes/functions.php';zorunlu_rol('admin','yonetici');

function turnuva_etiket($sira){$sira=(int)$sira-1;$etiket='';do{$etiket=chr(65+($sira%26)).$etiket;$sira=intdiv($sira,26)-1;}while($sira>=0);return $etiket;}
function turnuva_agacini_temizle($pdo,$turnuvaId){
    $q=$pdo->prepare('SELECT id FROM turnuva_maclari WHERE turnuva_id=?');$q->execute([$turnuvaId]);$maclar=array_map('intval',$q->fetchAll(PDO::FETCH_COLUMN));
    if($maclar){$yer=implode(',',array_fill(0,count($maclar),'?'));$pdo->prepare("DELETE FROM turnuva_sporcu_set_atislari WHERE turnuva_mac_id IN ($yer)")->execute($maclar);$pdo->prepare("DELETE FROM turnuva_mac_setleri WHERE turnuva_mac_id IN ($yer)")->execute($maclar);$pdo->prepare("DELETE FROM esitlik_bozma_atislari WHERE turnuva_mac_id IN ($yer)")->execute($maclar);}
    $pdo->prepare('DELETE FROM turnuva_maclari WHERE turnuva_id=?')->execute([$turnuvaId]);$pdo->prepare('DELETE FROM turnuva_eslesmeleri WHERE turnuva_id=?')->execute([$turnuvaId]);$pdo->prepare("UPDATE turnuvalar SET durum='taslak' WHERE id=?")->execute([$turnuvaId]);
}
function turnuva_agacini_kur($pdo,$turnuva,$hedefler){
    $turnuvaId=(int)$turnuva['id'];$kontenjan=(int)$turnuva['kontenjan'];
    if(count($hedefler)!==$kontenjan||count(array_unique($hedefler))!==$kontenjan)throw new RuntimeException('Kontenjan kadar, birbirinden farklı katılımcı seçmelisiniz.');
    turnuva_agacini_temizle($pdo,$turnuvaId);$pdo->prepare('DELETE FROM turnuva_katilimcilari WHERE turnuva_id=?')->execute([$turnuvaId]);
    $katilimciEkle=$pdo->prepare('INSERT INTO turnuva_katilimcilari(turnuva_id,hedef_id,sira) VALUES(?,?,?)');foreach($hedefler as $sira=>$hedef)$katilimciEkle->execute([$turnuvaId,$hedef,$sira+1]);
    $q=$pdo->prepare('SELECT id,hedef_id FROM turnuva_katilimcilari WHERE turnuva_id=? ORDER BY sira');$q->execute([$turnuvaId]);$katilimcilar=$q->fetchAll();
    $esEkle=$pdo->prepare('INSERT INTO turnuva_eslesmeleri(turnuva_id,tur_no,eslesme_no,katilimci1_id,katilimci2_id) VALUES(?,?,?,?,?)');$macEkle=$pdo->prepare('INSERT INTO turnuva_maclari(turnuva_id,eslesme_id,katilimci1_id,katilimci2_id,tur_no) VALUES(?,?,?,?,?)');
    $eslesmeNo=1;for($i=0;$i<$kontenjan;$i+=4){foreach([[$i,$i+2],[$i+1,$i+3]] as [$a,$b]){$esEkle->execute([$turnuvaId,1,$eslesmeNo++,$katilimcilar[$a]['id'],$katilimcilar[$b]['id']]);$esId=(int)$pdo->lastInsertId();$macEkle->execute([$turnuvaId,$esId,$katilimcilar[$a]['hedef_id'],$katilimcilar[$b]['hedef_id'],1]);}}
    $turSayisi=(int)round(log($kontenjan,2));for($tur=2;$tur<=$turSayisi;$tur++){for($no=1;$no<=$kontenjan/(2**$tur);$no++){$esEkle->execute([$turnuvaId,$tur,$no,null,null]);$esId=(int)$pdo->lastInsertId();$macEkle->execute([$turnuvaId,$esId,null,null,$tur]);}}
    $pdo->prepare("UPDATE turnuvalar SET durum='eslesme_hazir' WHERE id=?")->execute([$turnuvaId]);
}

$id=(int)($_GET['id']??$_POST['turnuva_id']??0);$sayfaIslem=$_GET['islem']??'';
if($_SERVER['REQUEST_METHOD']==='POST'){
    try{
        if(!csrf_check($_POST['csrf']??''))throw new RuntimeException('Güvenlik doğrulaması başarısız.');$islem=$_POST['islem']??'';
        if($islem==='turnuva_olustur'){
            $ad=trim($_POST['turnuva_adi']??'');$tur=$_POST['tur']??'takim';$kontenjan=(int)($_POST['kontenjan']??16);$sezonId=(int)($_POST['sezon_id']??0);
            if($ad===''||!in_array($tur,['takim','bireysel'],true)||!in_array($kontenjan,[16,32],true)||!$sezonId)throw new RuntimeException('Turnuva adı, türü, sezonu ve kontenjanı seçin.');
            $pdo->prepare('INSERT INTO turnuvalar(turnuva_adi,tur,kontenjan,sezon_id,aciklama) VALUES(?,?,?,?,?)')->execute([$ad,$tur,$kontenjan,$sezonId,trim($_POST['aciklama']??'')]);flash_set('basari','Turnuva oluşturuldu. Ağaç Oluştur ile katılımcıları seçebilirsiniz.');
        }elseif($islem==='agac_olustur'){
            $q=$pdo->prepare('SELECT * FROM turnuvalar WHERE id=?');$q->execute([$id]);$turnuva=$q->fetch();if(!$turnuva)throw new RuntimeException('Turnuva bulunamadı.');
            $hedefler=array_values(array_filter(array_map('intval',$_POST['katilimci']??[])));$pdo->beginTransaction();turnuva_agacini_kur($pdo,$turnuva,$hedefler);$pdo->commit();flash_set('basari','A–C ve B–D sıralamasına göre turnuva ağacı oluşturuldu.');
        }elseif($islem==='agaci_temizle'){
            $pdo->beginTransaction();turnuva_agacini_temizle($pdo,$id);$pdo->prepare('DELETE FROM turnuva_katilimcilari WHERE turnuva_id=?')->execute([$id]);$pdo->commit();flash_set('basari','Turnuva ağacı ve katılımcı yerleşimi temizlendi.');
        }elseif($islem==='turnuva_guncelle'){
            $ad=trim($_POST['turnuva_adi']??'');$sezonId=(int)($_POST['sezon_id']??0);if(!$id||$ad===''||!$sezonId)throw new RuntimeException('Turnuva adı ve sezon zorunludur.');$pdo->prepare('UPDATE turnuvalar SET turnuva_adi=?,sezon_id=?,aciklama=? WHERE id=?')->execute([$ad,$sezonId,trim($_POST['aciklama']??''),$id]);flash_set('basari','Turnuva bilgileri güncellendi.');
        }elseif($islem==='turnuva_sil'){
            $pdo->beginTransaction();turnuva_agacini_temizle($pdo,$id);$pdo->prepare('DELETE FROM turnuva_katilimcilari WHERE turnuva_id=?')->execute([$id]);$pdo->prepare('DELETE FROM turnuvalar WHERE id=?')->execute([$id]);$pdo->commit();flash_set('basari','Turnuva silindi.');
        }
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash_set('hata',$e->getMessage());}
    redirect(BASE_URL.'/admin/turnuvalar.php');
}

$sezonlar=$pdo->query("SELECT * FROM sezonlar WHERE durum='aktif' ORDER BY sezon_adi DESC")->fetchAll();$secili=null;$adaylar=[];
if($id&&in_array($sayfaIslem,['agac','duzenle'],true)){$q=$pdo->prepare('SELECT * FROM turnuvalar WHERE id=?');$q->execute([$id]);$secili=$q->fetch();if(!$secili){flash_set('hata','Turnuva bulunamadı.');redirect(BASE_URL.'/admin/turnuvalar.php');}if($sayfaIslem==='agac'){$adaylar=$secili['tur']==='takim'?$pdo->query('SELECT id,takim_adi ad FROM takimlar ORDER BY takim_adi')->fetchAll():$pdo->query("SELECT id,CONCAT(ad,' ',soyad) ad FROM sporcular ORDER BY ad,soyad")->fetchAll();}}
$liste=$pdo->query('SELECT t.*,COUNT(k.id) katilimci FROM turnuvalar t LEFT JOIN turnuva_katilimcilari k ON k.turnuva_id=t.id GROUP BY t.id ORDER BY t.created_at DESC')->fetchAll();
ob_start();
?>
<div class="lig-sayfa-iki-kolon">
<section class="card"><div class="card-head"><h2><?= $sayfaIslem==='duzenle'?'Turnuvayı Düzenle':'Yeni Turnuva' ?></h2></div>
<?php if($sayfaIslem==='duzenle'&&$secili): ?><form method="post" class="form"><?= csrf_field() ?><input type="hidden" name="islem" value="turnuva_guncelle"><input type="hidden" name="turnuva_id" value="<?= $id ?>"><div class="grid-2"><label>Turnuva adı *<input name="turnuva_adi" required value="<?= e($secili['turnuva_adi']) ?>"></label><label>Tür<input disabled value="<?= $secili['tur']==='takim'?'Takım Turnuvası':'Bireysel Turnuva' ?>"></label></div><div class="grid-2"><label>Katılımcı sayısı<input disabled value="<?= (int)$secili['kontenjan'] ?>"></label><label>Sezon *<select name="sezon_id"><?php foreach($sezonlar as $s): ?><option value="<?= (int)$s['id'] ?>" <?= (int)$secili['sezon_id']===(int)$s['id']?'selected':'' ?>><?= e($s['sezon_adi']) ?></option><?php endforeach; ?></select></label></div><label>Açıklama<textarea name="aciklama"><?= e($secili['aciklama']) ?></textarea></label><button class="btn btn-primary">Güncelle</button> <a class="btn btn-outline" href="<?= BASE_URL ?>/admin/turnuvalar.php">Vazgeç</a></form>
<?php else: ?><p class="muted">Turnuvayı oluşturun; katılımcıları daha sonra Ağaç Oluştur işleminden sıralı olarak yerleştirin.</p><form method="post" class="form"><?= csrf_field() ?><input type="hidden" name="islem" value="turnuva_olustur"><div class="grid-2"><label>Turnuva adı *<input name="turnuva_adi" required placeholder="Geleneksel Okçuluk Turnuvası"></label><label>Tür *<select name="tur"><option value="takim">Takım Turnuvası</option><option value="bireysel">Bireysel Turnuva</option></select></label></div><div class="grid-2"><label>Katılımcı sayısı *<select name="kontenjan"><option value="16">16 katılımcı</option><option value="32">32 katılımcı</option></select></label><label>Sezon *<select name="sezon_id"><?php foreach($sezonlar as $s): ?><option value="<?= (int)$s['id'] ?>"><?= e($s['sezon_adi']) ?></option><?php endforeach; ?></select></label></div><label>Açıklama<textarea name="aciklama"></textarea></label><button class="btn btn-primary">Turnuvayı Oluştur</button></form><?php endif; ?>
</section>
<section class="card"><div class="card-head"><h2>Oluşturulan Turnuvalar</h2><span class="badge"><?= count($liste) ?> turnuva</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Turnuva</th><th>Tür</th><th>Katılımcı</th><th>İşlem</th></tr></thead><tbody><?php foreach($liste as $x): ?><tr><td><?= e($x['turnuva_adi']) ?></td><td><?= $x['tur']==='takim'?'Takım':'Bireysel' ?></td><td><?= (int)$x['katilimci'].' / '.(int)$x['kontenjan'] ?></td><td class="actions"><a class="btn btn-sm btn-primary" href="<?= BASE_URL ?>/admin/turnuvalar.php?islem=agac&id=<?= (int)$x['id'] ?>">Ağaç Oluştur</a><form method="post" class="inline-form" onsubmit="return confirm('Bu turnuvanın ağacı ve katılımcı yerleşimi temizlensin mi?')"><?= csrf_field() ?><input type="hidden" name="islem" value="agaci_temizle"><input type="hidden" name="turnuva_id" value="<?= (int)$x['id'] ?>"><button class="btn btn-sm">Ağacı Temizle</button></form><a class="btn btn-sm" href="<?= BASE_URL ?>/admin/turnuvalar.php?islem=duzenle&id=<?= (int)$x['id'] ?>">Düzenle</a><form method="post" class="inline-form" onsubmit="return confirm('Turnuva tamamen silinsin mi?')"><?= csrf_field() ?><input type="hidden" name="islem" value="turnuva_sil"><input type="hidden" name="turnuva_id" value="<?= (int)$x['id'] ?>"><button class="btn btn-sm btn-danger">Sil</button></form></td></tr><?php endforeach; ?><?php if(!$liste): ?><tr><td colspan="4" class="muted">Henüz turnuva oluşturulmamış.</td></tr><?php endif; ?></tbody></table></div></section>
</div>

<?php if($sayfaIslem==='agac'&&$secili): ?><section class="card" style="margin-top:16px"><div class="card-head"><h2><?= e($secili['turnuva_adi']) ?> · Katılımcı Yerleşimi</h2><span class="badge"><?= (int)$secili['kontenjan'] ?> <?= $secili['tur']==='takim'?'takım':'sporcu' ?></span></div><p class="muted">Katılımcıları A, B, C, D… sırasıyla seçin. Aynı katılımcı ikinci kez seçilemez; A–C ve B–D eşleşmeleri otomatik kurulur.</p><form method="post" class="form" id="katilimci-formu"><?= csrf_field() ?><input type="hidden" name="islem" value="agac_olustur"><input type="hidden" name="turnuva_id" value="<?= $id ?>"><div class="grid-2"><?php for($i=0;$i<(int)$secili['kontenjan'];$i++): ?><label><?= turnuva_etiket($i+1) ?><select name="katilimci[]" class="katilimci-sec" required><option value="">Seçin</option><?php foreach($adaylar as $a): ?><option value="<?= (int)$a['id'] ?>"><?= e($a['ad']) ?></option><?php endforeach; ?></select></label><?php endfor; ?></div><div class="form-actions"><button class="btn btn-primary">Ağacı Oluştur</button><a class="btn btn-outline" href="<?= BASE_URL ?>/admin/turnuvalar.php">Vazgeç</a></div></form></section><script>document.querySelectorAll('.katilimci-sec').forEach(function(s){s.addEventListener('change',function(){var secilen=[].map.call(document.querySelectorAll('.katilimci-sec'),function(x){return x.value}).filter(Boolean);document.querySelectorAll('.katilimci-sec option').forEach(function(o){o.disabled=o.value!==''&&secilen.includes(o.value)&&o.parentElement.value!==o.value;});});});</script><?php endif; ?>
<?php $admin_baslik='Turnuvalar';$admin_aktif='turnuvalar';$admin_icerik=ob_get_clean();require __DIR__.'/partials/layout.php'; ?>
